Module: hexm.client.ui.windows.task.home_task_item.customize_item_consts
Type: table
================================================================================

Keys:
  HOME_TASK_ITEM_CONTENT: number
  refresh_task_item_text: function
  HOME_GUILD_MWZX_ITEM: string
  HOME_ONLINE_CALL: string
  HOME_TASK_ITEM_TITLE: number
  HOME_OPEN_YYPS_ITEM: string
  check_customize_is_button: function
  HOME_BLOCK_TASK_TIP: string
  home_task_item_template_adapter: function
  HOME_CLUB_BUIDING_GUIDE_2: string
  HOME_SCHOOL_CLUE_ITEM: string
  HOME_CLUB_BUIDING_GUIDE_1: string
  HOME_LEVEL_DETAIL: string
  HOME_CLUB_BUIDING_GUIDE_3: string
  check_customize_forbid_temp: function
  HOME_TASK_ITEM_RETURN: number
  try_leave_plot_recap: function
  MOBILE_BLOCK_TEMP_TRACK_WINDOWS: list
  get_all_task_item_clz: function
  HOME_TASK_ONLINE_TIP_SINGLE: number
  TASK_HUD_ITEM_CONFIG: dict
  HOME_INFERENCE_CLUE_ITEM: string
  HOME_TASK_ITEM_CLUE: number
  HOME_TASK_ITEM_SUB: number
  CUSTOMIZE_ITEM_RELATED_WINDOWS: list
  HOME_TASK_GUIDE_GOTO: string
  HOME_TASK_ITEM_DISTANCE: number
  HOME_TASK_ITEM_EMPTY_LIST: number
  HOME_GOOSE_THERAPY: string
  HOME_TASK_ONLINE_TIP_MULTI: number
  HOME_TASK_ITEM_MULTI_BUTTON: number
  HOME_LEAVE_PLOT_RECAP: string
  HOME_OPEN_EMAIL: string
  task_guide_goto_func: function
  HOME_FENBAO_LACK_ITEM: string