Module: patch.fenbao_consts
Type: table
================================================================================

Keys:
  FENBAO_LEVEL_HIGH: string
  FENBAO_DOWNLOAD_STATE_WAIT: number
  FENBAO_PRELOAD_PACKAGE_NAME: string
  is_in_baicaoye: function
  FENBAO_BTN_ICON_DOWNLOAD: string
  get_text_size: function
  FENBAO_PACKAGE_TYPE_PRELOAD: number
  FENBAO_ITEM_TYPE_CORE: number
  FENBAO_BTN_ICON_DOWNLOADING: string
  FENBAO_PACKAGE_TYPE_LANG: number
  FENBAO_PACKAGE_TYPE_EXTEND: number
  FENBAO_ICON_DOWNLOAD: string
  FENBAO_PRELOAD_PACKAGE: string
  FENBAO_DOWNLOAD_STATE_NONE: number
  FENBAO_BTN_ICON_WAIT: string
  FENBAO_ICON_DOWNLOADING: string
  FENBAO_PACKAGE_TYPE_CORE: number
  is_high2: function
  FENBAO_DOWNLOAD_STATE_DOWNLOAD: number
  get_main_player_package_id: function
  FENBAO_LOAD_STAGE_FINISH: number
  FENBAO_ICON_PAUSE: string
  FENBAO_PACKAGE_TYPE_VOICE: number
  is_fenbao_lang_in_use: function
  get_fenbao_reward_text: function
  FENBAO_BTN_ICON_START: string
  FENBAO_PATCH_STAGE_DOWNLOAD: number
  FENBAO_PRELOAD_PACKAGE_ID: number
  SUB_FENBAO_EXISTS: number
  FENBAO_TAB_CORE: number
  FENBAO_SRC_TYPE_ALL: list
  FENBAO_ITEM_TYPE_CORE_NORMAL: number
  SUB_FENBAO_NOT_EXISTS: number
  FENBAO_SRC_TYPE_VIDEO: number
  FENBAO_DOWNLOAD_STATE_DOWNLOADING: number
  need_fenbao_entry_visible: function
  FENBAO_SUB_WAIGUAN_SIZE_DISPLAY_FACTORY: number
  FENBAO_LEVEL_MID: string
  SUB_FENBAO_DOWNLOADING: number
  use_high2_waiguan: function
  show_tip: function
  FENBAO_LEVEL_LOW: string
  show_confirm_window: function
  FENBAO_BTN_ICON_PAUSE: string
  FENBAO_DOWNLOAD_STATE_PAUSE: number
  FENBAO_RED_POINT_NEW_PACKAGE: string
  FENBAO_DOWNLOAD_STATE_FINISH: number
  FENBAO_SRC_TYPE_WAIGUAN: number
  FENBAO_TAB_PRELOAD: number
  FENBAO_RED_POINT_RELOGIN: string
  (1 more keys)