Module: patch.netdetecter
Type: table
================================================================================

Keys:
  SCENE_UNEXPEXT_OFFLINE: number
  SCENE_DELAY: number
  SCENE_DOWNLOAD_PATCH_FAILED: number
  SCENE_PATCHING_CANCELED: number
  detect: function(scenetype, detect_model)  -- patch/netdetecter.lua:205-230
  MOBILE_TYPE: string
  SCENE_PAYMENT_SUCCESS: number
  GAME_STAGE: string
  SCENE_PATCH_JOIN: number
  GAMESTATUS_DOMAIN: string
  DL_SPEED: string
  SCENE_GAME_RECONNECT: number
  SCENE_LOST_PACKETS: number
  SCENE_DOWNLOAD_PATCH_LIST_SUCCESS: number
  PATCH_START_TIME: string
  SCENE_INITIAL_SUCCESS: number
  SCENE_DOWNLOAD_SERVER_LIST_FAILED: number
  ProductOversea: string
  SERVER_NAME: string
  FRAMERATEAVG: string
  URL: string
  SERVERLIST_URL: string
  SCENE_PATCH_START: number
  SCENE_PATCH_SUCCESS_EXTEND_START: number
  HTTP_CODE: string
  SCENE_DOWNLOAD_PATCH_LIST_CANCELED: number
  FILE_MD5: string
  SCENE_CONNECT_TO_SERVER_SUCCESS: number
  SCENE_URL_CONNECTIVITY_REACHABLE: number
  SCENE_APP_VISIT_SUCCESS: number
  SCENE_PAYMENT_FAILED: number
  DP: string
  FILE_SIZE: string
  DEVICE_ID: string
  SCENE_DOWNLOAD_PATCH_LIST_FAILED: number
  LAGFRAMERATE: string
  SCENE_GAME_START: number
  SCENE_CONNECT_TO_SERVER_FAILED: number
  MEM_IDLE: string
  SCENE_PATCH_END: number
  USER_ID: string
  SERVER_PORT: string
  CHANNEL_NAME: string
  detect_init: function()  -- patch/netdetecter.lua:193-203
  PATCH_CHECK_RESULT: string
  PATCH_FINISH_TIME: string
  PATCH_URL: string
  FILE_NUM: string
  SERVER_IP: string
  FILE_MD5_RESULT: string
  SCENE_SIGIN_SUCCESS: number
  SCENE_APP_VISIT_FAILED: number
  USER_NAME: string
  UPLOAD_DOMAIN: string
  SCENE_VOICE_ABNORMAL: number
  SCENE_URL_CONNECTIVITY_UNREACHABLE: number
  SCENE_SIGIN_FAILED: number
  NETWORK_TYPE: string
  CPU_CLOCKSPEED: string
  DETECT_OPEN: boolean
  SCENE_PATCH_FAILED_EXTEND_START: number
  SCENE_PATCH_FAILED_EXTEND_END: number
  Product: string
  SCENE_LOCATION: string
  SCENE_PATCH_SUCCESS_EXTEND_END: number
  SCENE_DOWNLOAD_SERVER_LIST_SUCCESS: number
  MEM_TOTAL: string
  FACES: string
  PATCH_VERSION: string
  PATCHLIST_URL: string
  TIME_COST: string
  ACCOUNT: string
  VOICE_DOWNLOAD: string
  SCENE_DOWNLOAD_PATCH_SUCCESS: number
  NEED_DOWNLOAD_SIZE: string
  LogOpen: boolean
  DOWNLOAD_NEWPATCH: string
  DOWNLOAD_ID: string
  SCENE_INITIAL_FAILED: number
  detect_set_prop: function(prop_dict)  -- patch/netdetecter.lua:175-191
  SCENE_DOWNLOAD_SERVER_LIST_CANCELED: number
  DNSUP_DOMAIN: string
  SCENE_COLLECTION_NORMAL: number
  PRE_PATCH_SIZE: string
  ERROR_LOG: string
  SCENE_GAME_SLOWNESS: number
  VOICE_TRANSLATE: string
  SCENE_DOWNLOAD_PATCH_CANCELED: number
  UNZIP: string
  TRANSID: string
  OS_VERSION: string
  CPU_MODEL: string
  OS: string
  VOICE_UPLOAD: string
  PLAY_STAGE: string