Module: asiocore
Type: table
================================================================================

Keys:
  get_props_profile_period: function(...)  -- =[C]
  get_default_zstd_compress_level: function(...)  -- =[C]
  get_class: function(...)  -- =[C]
  b64decode: function(...)  -- =[C]
  set_kcp_sync_magic: function(...)  -- =[C]
  get_kcp_vginfo: function(...)  -- =[C]
  udp_ping: class <udp_ping>
    Functions:
      ping(...)  -- =[C]
      get_count(...)  -- =[C]
      set_timeout(...)  -- =[C]
      ctor(...)  -- =[C]
      set_count(...)  -- =[C]
      get_timeout(...)  -- =[C]
      new(...)  -- =[C]
  get_lua_callback_execute_stats: function(...)  -- =[C]
  get_string_indexes: function(...)  -- =[C]
  setting: class <setting>
    Functions:
      get_dist_aoi(...)  -- =[C]
      get_mult_scope(...)  -- =[C]
      set_enable_zstd(...)  -- =[C]
      set_msgpackrpc_client(...)  -- =[C]
      get_enable_custom_props_simple_cast_trace(...)  -- =[C]
      get_auto_apply_cached_area_message(...)  -- =[C]
      get_msgpackrpc_client(...)  -- =[C]
      set_enable_string_index(...)  -- =[C]
      get_area_map_bucket_hint(...)  -- =[C]
      get_enable_string_index(...)  -- =[C]
      get_keep_prev_prop_obj(...)  -- =[C]
      set_dist_aoi(...)  -- =[C]
      set_mult_scope(...)  -- =[C]
      new(...)  -- =[C]
      set_keep_prev_prop_obj(...)  -- =[C]
      set_enable_telnet_tab_completion(...)  -- =[C]
      set_crypto(...)  -- =[C]
      set_auto_apply_cached_area_message(...)  -- =[C]
      set_enable_string_statistic(...)  -- =[C]
      get_enable_custom_props_cast(...)  -- =[C]
      set_pos_ignore(...)  -- =[C]
      get_enable_string_statistic(...)  -- =[C]
      set_enable_custom_props_simple_cast_trace(...)  -- =[C]
      set_enable_custom_props_cast(...)  -- =[C]
      get_crypto(...)  -- =[C]
      get_enable_telnet_tab_completion(...)  -- =[C]
      ctor(...)  -- =[C]
      get_enable_zstd(...)  -- =[C]
      set_area_map_bucket_hint(...)  -- =[C]
      get_pos_ignore(...)  -- =[C]
  get_prop_index: function(...)  -- =[C]
  get_tcp_keepcnt: function(...)  -- =[C]
  get_timer_info: function(...)  -- =[C]
  set_login_key: function(...)  -- =[C]
  get_fec_grade_symbol_len: function(...)  -- =[C]
  set_tcp_keepcnt: function(...)  -- =[C]
  get_snd_share_count: function(...)  -- =[C]
  KCP_FEC_REED_SOLOMON: number
  set_snd_share_count: function(...)  -- =[C]
  stamp: function(...)  -- =[C]
  kcp_set_poll_interval: function(...)  -- =[C]
  set_default_zstd_compress_level: function(...)  -- =[C]
  set_max_frame_us: function(...)  -- =[C]
  enabled_pos_unreliable: function(...)  -- =[C]
  bhttps_client: class <bhttps_client>
    Functions:
      get_keep_alive(...)  -- =[C]
      set_response_body_limit(...)  -- =[C]
      get_ip_protocols(...)  -- =[C]
      get_response_body_limit(...)  -- =[C]
      get_active(...)  -- =[C]
      set_ip_protocols(...)  -- =[C]
      ctor(...)  -- =[C]
      start(...)  -- =[C]
      release(...)  -- =[C]
      new(...)  -- =[C]
  async_connection: class <async_connection>
    Functions:
      set_recv_limit(...)  -- =[C]
      release(...)  -- =[C]
      set_buffer_size(...)  -- =[C]
      get_sndbuf(...)  -- =[C]
      clear_handler(...)  -- =[C]
      set_local_port(...)  -- =[C]
      set_handler(...)  -- =[C]
      set_nop_itvl(...)  -- =[C]
      get_local_port(...)  -- =[C]
      handle_read(...)  -- =[C]
      handle_connected(...)  -- =[C]
      get_send_limit(...)  -- =[C]
      new(...)  -- =[C]
      handle_close(...)  -- =[C]
      set_sndbuf(...)  -- =[C]
      async_write(...)  -- =[C]
      set_connected_timeout(...)  -- =[C]
      set_send_limit(...)  -- =[C]
      set_rcvbuf(...)  -- =[C]
      get_nop_itvl(...)  -- =[C]
      connect(...)  -- =[C]
      get_netinfo(...)  -- =[C]
      get_rcvbuf(...)  -- =[C]
      disconnect(...)  -- =[C]
      get_connected_timeout(...)  -- =[C]
      ctor(...)  -- =[C]
      set_local_ip(...)  -- =[C]
      get_buffer_size(...)  -- =[C]
      get_local_ip(...)  -- =[C]
  get_classes: function(...)  -- =[C]
  set_prop_index: function(...)  -- =[C]
  set_fec_max_level: function(...)  -- =[C]
  get_kcp_ignore_socket_error: function(...)  -- =[C]
  get_thread_num: function(...)  -- =[C]
  get_props_profile_result: function(...)  -- =[C]
  set_kcp_ignore_socket_error: function(...)  -- =[C]
  get_fec_switch: function(...)  -- =[C]
  start_worker_delay_timer: function(...)  -- =[C]
  revision: function(...)  -- =[C]
  get_fec_max_level: function(...)  -- =[C]
  set_kcp_newstyle_handshake: function(...)  -- =[C]
  get_debug_rpc: function(...)  -- =[C]
  set_fec_rate: function(...)  -- =[C]
  set_fec_switch: function(...)  -- =[C]
  set_thread_num: function(...)  -- =[C]
  get_kcp_sync_magic: function(...)  -- =[C]
  _debug_only_do_not_call_it_crashes_: function(...)  -- =[C]
  IS_CLIENT_ONLY: number
  time: function(...)  -- =[C]
  get_fec_rate: function(...)  -- =[C]
  area: class <area>
    Functions:
      get_id(...)  -- =[C]
      call_server(...)  -- =[C]
      stop_spectator_record(...)  -- =[C]
      set_direction(...)  -- =[C]
      todict(...)  -- =[C]
      set_handler(...)  -- =[C]
      set_exclude_guid(...)  -- =[C]
      get_exclude_guid(...)  -- =[C]
      get_cached_entities(...)  -- =[C]
      dist_aoi_pick(...)  -- =[C]
      set__center(...)  -- =[C]
      get_send_position_callback(...)  -- =[C]
      set_speed(...)  -- =[C]
      get__center(...)  -- =[C]
      set_inspace(...)  -- =[C]
      clear_on_enter_space(...)  -- =[C]
      get_guid(...)  -- =[C]
      set_top_speed(...)  -- =[C]
      get_debug_rpc(...)  -- =[C]
      on_enter_space(...)  -- =[C]
      get_name(...)  -- =[C]
      set_debug_rpc(...)  -- =[C]
      set_yaw(...)  -- =[C]
      has_update_aoi_info_callback_incar(...)  -- =[C]
      get_debug(...)  -- =[C]
      set_update_aoi_info_callback(...)  -- =[C]
      get_direction(...)  -- =[C]
      get_send_position_callback_incar(...)  -- =[C]
      interest_aoi(...)  -- =[C]
      get_top_speed(...)  -- =[C]
      set_rposition(...)  -- =[C]
      get_rposition(...)  -- =[C]
      has_update_aoi_info_callback(...)  -- =[C]
      prop(...)  -- =[C]
      play_spectator_speed(...)  -- =[C]
      set_position(...)  -- =[C]
      get_position(...)  -- =[C]
      get_speed(...)  -- =[C]
      set_update_aoi_info_callback_incar(...)  -- =[C]
      set_debug(...)  -- =[C]
      in_aoi(...)  -- =[C]
      new(...)  -- =[C]
      set_cached_entity_priority(...)  -- =[C]
      apply_cached_area_message(...)  -- =[C]
      set_cid(...)  -- =[C]
      get_yaw(...)  -- =[C]
      get_cid(...)  -- =[C]
      owner(...)  -- =[C]
      get_scopeno(...)  -- =[C]
      get_space(...)  -- =[C]
  add_timer: function(...)  -- =[C]
  set_props_profile_period: function(...)  -- =[C]
  cancel_worker_delay_timer: function(...)  -- =[C]
  dump_string_statistic: function(...)  -- =[C]
  http_error_types: table <UnknownInstance>
  set_kcp_mh_handshake: function(...)  -- =[C]
  pop_insight_stats: function(...)  -- =[C]
  set_py_callback_execute_limit: function(...)  -- =[C]
  set_process_name: function(...)  -- =[C]
  rpc_handler: class <rpc_handler>
    Functions:
      set_window_bits(...)  -- =[C]
      set_mem_level(...)  -- =[C]
      dispatch_rpc(...)  -- =[C]
      get_scope(...)  -- =[C]
      getpeername(...)  -- =[C]
      enable_encrypter(...)  -- =[C]
      disconnect(...)  -- =[C]
      enable_compressor(...)  -- =[C]
      ctor(...)  -- =[C]
      enable_zstd(...)  -- =[C]
      new(...)  -- =[C]
  get_kcp_vgate: function(...)  -- =[C]
  clear_prop_index: function(...)  -- =[C]
  get_msg_cache_limit: function(...)  -- =[C]
  set_enable_insight_stat: function(...)  -- =[C]
  get_default_win_bits: function(...)  -- =[C]
  get_lua_callback_total_execute_stats: function(...)  -- =[C]
  area_list_iter_obj: class <area_list_iter_obj>
    Functions:
      __close(...)  -- =[C]
      ctor(...)  -- =[C]
      new(...)  -- =[C]
  get_recv_bytes: function(...)  -- =[C]
  set_tcp_keepidle: function(...)  -- =[C]
  set_worker_delay_callback: function(...)  -- =[C]
  get_process_name: function(...)  -- =[C]
  enable_pos_unreliable: function(...)  -- =[C]
  set_entity_class_callback: function(...)  -- =[C]
  get_insight_stats: function(...)  -- =[C]
  entities: function(...)  -- =[C]
  set_recv_bytes: function(...)  -- =[C]
  refresh_random_seed: function(...)  -- =[C]
  get_loop_time: function(...)  -- =[C]
  set_enable_lua_callback_stat: function(...)  -- =[C]
  service_type: table <UnknownInstance>
  patch_area_map: function(...)  -- =[C]
  get_kcp_newstyle_handshake: function(...)  -- =[C]
  enable_kcp_dupack: function(...)  -- =[C]
  get_kcp_sync_magic_orig: function(...)  -- =[C]
  set_props_profile: function(...)  -- =[C]
  KCP_FEC_XOR_COMPACT: number
  set_msg_cache_limit: function(...)  -- =[C]
  set_default_mem_level: function(...)  -- =[C]
  area_map_iter_obj: class <area_map_iter_obj>
    Functions:
      __close(...)  -- =[C]
      ctor(...)  -- =[C]
      new(...)  -- =[C]
  clear_area_message: function(...)  -- =[C]
  set_loop_time: function(...)  -- =[C]
  set_send_bytes: function(...)  -- =[C]
  enable_reliable: function(...)  -- =[C]
  set_py_callback_total_execute_limit: function(...)  -- =[C]
  wheeltimer: table <UnknownInstance>
    Functions:
      cancel_all_run_once_timers(...)  -- =[C]
      has_timer(...)  -- =[C]
      add_timer(...)  -- =[C]
      set_enabled(...)  -- =[C]
      update(...)  -- =[C]
      get_timer_count(...)  -- =[C]
      set_slot_step(...)  -- =[C]
      cancel_all_timers(...)  -- =[C]
      cancel_timer(...)  -- =[C]
  poll: function(...)  -- =[C]
  get_py_callback_execute_limit: function(...)  -- =[C]
  enabled_reliable: function(...)  -- =[C]
  debug_dangerous_get_object: function(...)  -- =[C]
  set_kcp_vgate: function(...)  -- =[C]
  set_tcp_keepintvl: function(...)  -- =[C]
  hex_revision: function(...)  -- =[C]
  get_kcp_mh_handshake: function(...)  -- =[C]
  get_py_callback_total_execute_limit: function(...)  -- =[C]
  del_timer: function(...)  -- =[C]
  set_fec_grade_symbol_len: function(...)  -- =[C]
  set_kcp_vginfo: function(...)  -- =[C]
  get_lua_callback_stats: function(...)  -- =[C]
  add_string_indexes: function(...)  -- =[C]
  get_fec_codec: function(...)  -- =[C]
  b64encode: function(...)  -- =[C]
  stop: function(...)  -- =[C]
  get_tcp_keepintvl: function(...)  -- =[C]
  async_kcp_connection: class <async_kcp_connection>
    Functions:
      get_netstats_max_retrans_count(...)  -- =[C]
      local_addr(...)  -- =[C]
      get_dropcount(...)  -- =[C]
      get_netstats_enabled(...)  -- =[C]
      get_ignore_socket_error(...)  -- =[C]
      set_netstats_enabled(...)  -- =[C]
      async_write(...)  -- =[C]
      set_handler(...)  -- =[C]
      set_timeout(...)  -- =[C]
      get_netstats_max_send_size(...)  -- =[C]
      set_ignore_socket_error(...)  -- =[C]
      get_netstats_avg_rtt(...)  -- =[C]
      set_rcvwnd(...)  -- =[C]
      set_rcvbuf(...)  -- =[C]
      get_netstats_min_send_size(...)  -- =[C]
      get_timeout(...)  -- =[C]
      set_send_limit(...)  -- =[C]
      get_netstats_total_send_count(...)  -- =[C]
      set_nodelay(...)  -- =[C]
      get_sndbuf(...)  -- =[C]
      set_nocwnd(...)  -- =[C]
      get_send_limit(...)  -- =[C]
      set_sndbuf(...)  -- =[C]
      get_netstats_total_retrans_count(...)  -- =[C]
      release(...)  -- =[C]
      get_buffer_size(...)  -- =[C]
      get_nocwnd(...)  -- =[C]
      get_split_limit(...)  -- =[C]
      set_dropwindow(...)  -- =[C]
      set_connected_timeout(...)  -- =[C]
      get_srttvalue(...)  -- =[C]
      get_netstats_rtt_buckets(...)  -- =[C]
      clear_handler(...)  -- =[C]
      get_dropwindow(...)  -- =[C]
      set_interval(...)  -- =[C]
      set_split_limit(...)  -- =[C]
      ctor(...)  -- =[C]
      get_check_itvl(...)  -- =[C]
      set_stream(...)  -- =[C]
      get_rcvwnd(...)  -- =[C]
      get_mh_ver(...)  -- =[C]
      get_stream(...)  -- =[C]
      get_connected_timeout(...)  -- =[C]
      set_check_itvl(...)  -- =[C]
      handle_close(...)  -- =[C]
      set_sndwnd(...)  -- =[C]
      connect(...)  -- =[C]
      get_nodelay(...)  -- =[C]
      get_netstats_total_send_bytes(...)  -- =[C]
      get_sndwnd(...)  -- =[C]
  area_map: class <area_map>
    Functions:
      __len(...)  -- =[C]
      __eq(...)  -- =[C]
      __pairs(...)  -- =[C]
      __tostring(...)  -- =[C]
      props_all(...)  -- =[C]
      get_owner(...)  -- =[C]
      update(...)  -- =[C]
      todict(...)  -- =[C]
      copy(...)  -- =[C]
      setdefault(...)  -- =[C]
      normal_pairs(...)  -- =[C]
      size(...)  -- =[C]
      clear(...)  -- =[C]
      get_parent(...)  -- =[C]
      pop(...)  -- =[C]
      total_size(...)  -- =[C]
      dsize(...)  -- =[C]
      new(...)  -- =[C]
      ctor(...)  -- =[C]
      contains(...)  -- =[C]
      get(...)  -- =[C]
      weak_dict(...)  -- =[C]
  set_fec_switch_disable: function(...)  -- =[C]
  set_fec_grade: function(...)  -- =[C]
  telnet_server: class <telnet_server>
    Functions:
      broadcast(...)  -- =[C]
      stop(...)  -- =[C]
      ctor(...)  -- =[C]
      bind(...)  -- =[C]
      new(...)  -- =[C]
      listen(...)  -- =[C]
  async_server: class <async_server>
    Functions:
      set_recv_limit(...)  -- =[C]
      get_sndbuf(...)  -- =[C]
      set_reuse_addr(...)  -- =[C]
      listen(...)  -- =[C]
      set_nop_itvl(...)  -- =[C]
      bind(...)  -- =[C]
      reset_connection(...)  -- =[C]
      new(...)  -- =[C]
      set_sndbuf(...)  -- =[C]
      set_rcvbuf(...)  -- =[C]
      get_rcvbuf(...)  -- =[C]
      stop(...)  -- =[C]
      get_connected_timeout(...)  -- =[C]
      ctor(...)  -- =[C]
      get_nop_itvl(...)  -- =[C]
      set_connected_timeout(...)  -- =[C]
  bhttp_client: class <bhttp_client>
    Functions:
      get_keep_alive(...)  -- =[C]
      set_response_body_limit(...)  -- =[C]
      get_ip_protocols(...)  -- =[C]
      get_response_body_limit(...)  -- =[C]
      get_active(...)  -- =[C]
      set_ip_protocols(...)  -- =[C]
      ctor(...)  -- =[C]
      start(...)  -- =[C]
      release(...)  -- =[C]
      new(...)  -- =[C]
  set_process_id: function(...)  -- =[C]
  KCP_FEC_XOR: number
  regist_class: function(...)  -- =[C]
  clear_class: function(...)  -- =[C]
  set_default_win_bits: function(...)  -- =[C]
  get_tcp_keepidle: function(...)  -- =[C]
  http_client: class <http_client>
    Functions:
      start(...)  -- =[C]
      ctor(...)  -- =[C]
      set_buffer_size(...)  -- =[C]
      get_buffer_size(...)  -- =[C]
      new(...)  -- =[C]
  get_enable_lua_callback_stat: function(...)  -- =[C]
  area_prop_index: class <area_prop_index>
    Functions:
      indexes(...)  -- =[C]
      rflag(...)  -- =[C]
      props(...)  -- =[C]
      object(...)  -- =[C]
      ispec_type(...)  -- =[C]
      ctor(...)  -- =[C]
      spec_type(...)  -- =[C]
      new(...)  -- =[C]
  entity: class <entity>
    Functions:
      notify_debug_info(...)  -- =[C]
      get_area(...)  -- =[C]
      del_prop_notify(...)  -- =[C]
      ctor(...)  -- =[C]
      set_area(...)  -- =[C]
      add_prop_notify(...)  -- =[C]
      new(...)  -- =[C]
  clear_string_statistic: function(...)  -- =[C]
  set_fec_switch_enable: function(...)  -- =[C]
  get_process_id: function(...)  -- =[C]
  region_mgr: class <region_mgr>
    Functions:
      reg_area(...)  -- =[C]
      dump_tree(...)  -- =[C]
      add_shapes(...)  -- =[C]
      get_overlap(...)  -- =[C]
      add_shape(...)  -- =[C]
      modify_shape(...)  -- =[C]
      enable_shape(...)  -- =[C]
      tick(...)  -- =[C]
      ctor(...)  -- =[C]
      unreg_area(...)  -- =[C]
      remove_shape(...)  -- =[C]
      new(...)  -- =[C]
  check_watcher: function(...)  -- =[C]
  set_debug_rpc: function(...)  -- =[C]
  del_all_timers: function(...)  -- =[C]
  get_fec_grade: function(...)  -- =[C]
  set_fec_codec: function(...)  -- =[C]
  get_enable_insight_stat: function(...)  -- =[C]
  enabled_kcp_dupack: function(...)  -- =[C]
  get_send_bytes: function(...)  -- =[C]
  remove_class: function(...)  -- =[C]
  poll_ex: function(...)  -- =[C]
  set_fast_send: function(...)  -- =[C]
  start: function(...)  -- =[C]
  get_props_profile: function(...)  -- =[C]
  get_default_mem_level: function(...)  -- =[C]
  area_list: class <area_list>
    Functions:
      __len(...)  -- =[C]
      __pairs(...)  -- =[C]
      __tostring(...)  -- =[C]
      index(...)  -- =[C]
      assign(...)  -- =[C]
      get_owner(...)  -- =[C]
      update(...)  -- =[C]
      tolist(...)  -- =[C]
      slice(...)  -- =[C]
      unpack(...)  -- =[C]
      new(...)  -- =[C]
      clear(...)  -- =[C]
      get_parent(...)  -- =[C]
      insert(...)  -- =[C]
      pop(...)  -- =[C]
      append(...)  -- =[C]
      delete(...)  -- =[C]
      size(...)  -- =[C]
      ctor(...)  -- =[C]
      sorted(...)  -- =[C]
      extend(...)  -- =[C]
      contains(...)  -- =[C]
      copy(...)  -- =[C]
      get(...)  -- =[C]