Module: debug
Type: table
================================================================================

Keys:
  getfuncextra: function(...)  -- =[C]
  getlogprefix: function(...)  -- =[C]
  getuservalue: function(...)  -- =[C]
  GCHead: function(...)  -- =[C]
  gethook: function(...)  -- =[C]
  upvalueid: function(...)  -- =[C]
  traceback: function(...)  -- =[C]
  upvaluejoin: function(...)  -- =[C]
  setlogprefix: function(...)  -- =[C]
  setuservalue: function(...)  -- =[C]
  getlocal: function(...)  -- =[C]
  getupvalue: function(...)  -- =[C]
  getmetatable: function(...)  -- =[C]
  is_func_from_module: function(...)  -- =[C]
  setmetatable: function(...)  -- =[C]
  GCNext: function(...)  -- =[C]
  setfuncextra: function(...)  -- =[C]
  copysource: function(...)  -- =[C]
  getinfo: function(...)  -- =[C]
  sethook: function(...)  -- =[C]
  update_proto: function(...)  -- =[C]
  dis: function(...)  -- =[C]
  setlocal: function(...)  -- =[C]
  setupvalue: function(...)  -- =[C]
  setcstacklimit: function(...)  -- =[C]
  getregistry: function(...)  -- =[C]
  debug: function(...)  -- =[C]