Module: hexm.client.ui.windows.dress_station.dress_station_consts
Type: table
================================================================================

Keys:
  T_MARKED: string
  TAB_HOT: number
  is_artwork_code: function
  PUBLISH_ZHUANGRONG: string
  T_HOT_TODAY: string
  OPERATE_LIAOTIAN: number
  APPLY_WORK_QRCODE: number
  forbid_trc_beta_r5304: function
  forbid_trc_beta_qrcode: function
  ICON_RATIO_3_4: number
  T_DESIGNER: string
  RPC_MIN_GAP: number
  USE_REUSED_FALLS_CONTROLLER: boolean
  PUBLISH_TITLE_DEFAULT: number
  TAB_TYPE_TO_VIEW_TYPE: dict
  ICON_RATIO_4_3: number
  T_HOT_WEEKLY: string
  SORT_TYPE_TO_TEXT: dict
  refresh_dress_station_text: function
  DYE_TYPE_FILTER: list
  T_FOLLOW: number
  TAB_MARKED: number
  OPERATE_TO_PNG: dict
  ICON_RATIO_TO_DIBAN_SIZE: dict
  TAB_DESIGNER: number
  T_EDIT_PUBLISH_TEXT: string
  T_MINE: string
  get_dress_station_icon_nimi: function
  T_DESIGNER_SHAIXUAN: string
  APPLY_WORK_DYE: number
  TYPE_NOT_OPEN: string
  ICON_RATION_TOTAL: number
  OPERATE_OPEN_MAINPAGE: number
  PUBLISH_PRIVATE: string
  APPLY_ONLY_FASHION: number
  OPERATE_ADD_FRIEND: number
  ICON_RATIO_1_1: number
  get_dress_station_icon: function
  T_MINE_SHAIXUAN: string
  ICON_RATIO_TO_MASK_SIZE: dict
  ICON_RATIO_TO_RECOMMEND_SIZE: dict
  T_HOT: string
  forbid_trc_beta_r5061: function
  get_dress_station_offical_player: function
  APPLY_WORK_ID: number
  SUB_TAB_TO_PNG: dict
  is_equal_artwork_data: function
  SUB_TAB_TO_NAME: dict
  APPLY_GOTO_FACE: number
  PUBLISH_TITLE_CONTENT: number
  (1 more keys)