Module: hexm.client.entities.local.player_avatar_members.langzhong.doctor_utils
Type: table
================================================================================

Keys:
  THERAPY_INTERRUPT_EVENT_LEAVE_SPACE_LEVEL: number
  multi_therapy_position: function
  ERR_UNDIAGNOSABLE_MISSING_TARGET: number
  OPMODE_DETAIL: string
  MULTI_THERAPY_PATIENT_BUFF: number
  E_CALLBACK_THERAPY_START_OK: string
  PVP_ANYING: number
  S_SETTLEMENT: string
  PATIENT_ANSWER_STATE_INIT: number
  E_CALLBACK_THERAPY_START_FAIL: string
  PVP_LANGZHONG_TOKEN_TYPE: number
  SPECIAL_DAM_DISCARD_ALL: number
  K_SETTLEMENT: string
  S_DIAGNOSE_PREPARE: string
  MARK_SYS_D_KEY: dict
  OK: number
  BUFF_TARGET_SELF: number
  BUFF_TARGET_TARGET: number
  THERAPY_INTERRUPT_EVENT_ABANDON_BY_IDENTITY: string
  THERAPY_INTERRUPT_EVENT_ABANDON_BY_PATIENT: number
  R_POSTCONDITION_FAIL: string
  MULTI_THERAPY_STATE_GAME: number
  USE_ENEMY_SINGLE: number
  is_identity_baiye: function
  SKILL_TAG_RES: number
  PVP_JIESUAN_ONE_ROUND_END: number
  THERAPY_INTERRUPT_EVENT_LOSE_CLIENT: number
  X_THERAPY_START_FAIL: string
  X_IN_BATTLE: string
  WUDAO_KEY: string
  E_DIAGNOSE_DOCTOR_LEFT: string
  SPECIAL_DAM_HURT_SELF: number
  PVP_WUDAO: number
  R_PRECONDITION_FAIL: string
  CONSUME_ETHEREAL: number
  SKILL_TAG_ATK: number
  require_doctor_module: function
  BAIYE: number
  PVP_LANGZHONG: number
  THERAPY_INTERRUPT_EVENT_ABANDON_BY_DOCTOR: number
  S_THERAPY_SUSPEND: string
  is_middle_camp: function
  get_multi_therapy_sync_id_twins_pos: function
  USE_SELF: number
  get_team_wudao_pid: function
  E_ROLE_PREPARED: string
  ERR_UNDIAGNOSABLE_DEAD: number
  get_pvp_identity_text: function
  LAUNCH_VOTE: number
  DEAL_APPLY_WUDAO: number
  (1 more keys)