Module: hexm.client.ui.windows.chat.chat_window_events
Type: table
================================================================================

Keys:
  get_is_single_prison_group_chat: function
  chat_tongzhi_post_news: string
  get_normal_msg_content: function
  chat_tongzhi_painting_boat_applied: string
  chat_tab_icons: dict
  chat_tongzhi_type_activity: string
  group_manage_type_manage: string
  chat_tongzhi_type_reply: string
  group_manage_type_create: string
  event_group_manage_real_select_players: string
  get_is_group_id_jieyi_group_chat: function
  chat_friend_type_black: string
  event_on_focus_lv2_tab: string
  get_hud_not_show_channels: function
  event_group_manage_head_focus: string
  chat_anony_type_pray: string
  chat_room_type_mine: string
  event_group_manage_right_player_cancel_clicked: string
  event_group_manage_head_clicked: string
  chat_friend_type_friend_apply: string
  chat_room_type_favorite: string
  chat_friend_type_friend: string
  check_oversea_social_limit_notify: function
  event_group_manage_left_all_players_clicked: string
  event_group_manage_selector_clicked: string
  chat_tab_channel: string
  is_msg_type_show_in_danmu: function
  chat_tab_anony: string
  chat_channel_type_group: string
  chat_emotion_type_custom: string
  chat_friend_type_group: string
  chat_room_type_chatroom: string
  event_on_click_lv2_tab: string
  chat_channel_type_lupai: string
  chat_channel_type_private_empty: string
  get_lv2_tab_is_show: function
  event_on_lv2_tab_changed: string
  chat_group_lupai_no_select: string
  chat_tab_private: string
  check_is_npc_msg: function
  get_system_msg_content: function
  event_group_data_finish: string
  chat_tongzhi_type_notify: string
  group_manage_window_selector_friend: string
  event_group_manage_select_box_clicked: string
  chat_channel_type_private: string
  get_hud_if_not_show_channel: function
  friend_tab_name_dict: dict
  get_danmu_show: function
  get_friend_tab_name: function
  (1 more keys)