Module: hexm.client.ui.windows.xuanshang.xuanshang_consts
Type: table
================================================================================

Keys:
  PUBLISHER: number
  XS_PUBLISH_ITEM_TYPE_DISEASE: number
  XS_LIMIT_DEFAULT_MEMBER_LOW: number
  XS_DETAIL_ITEM_TYPE_DISEASE: number
  kill_data_get_nickname: function
  get_space_and_region_text: function
  kill_data_get_description: function
  XS_PUBLISH_ITEM_TYPE_REWARD: number
  SOCIAL_TYPE_DOCTOR: number
  XS_TYPE_KILL: number
  XS_V2_DIFFICULT_MIDDLE_LEVEL: number
  XS_V2_DIFFICULT_HARD_LEVEL: number
  XS_DETAIL_ITEM_TYPE_KILL_INFO: number
  XS_DETAIL_ITEM_TYPE_STUFF: number
  FETCHER: number
  XS_PUBLISH_DISEASE_MODE: number
  XS_TAB_MINE_FETCH: number
  SOCIAL_TYPE_DEBATE: number
  XS_CHOUSHA_PLAYER: number
  XS_DETAIL_WINDOW_TYPE_ACCEPT: number
  XS_TAB_VIEW: number
  XS_V2_DIFFICULT_SIMPLE_LEVEL: number
  XS_PUBLISH_TARGET_MODE: number
  XS_DETAIL_ITEM_TYPE_REWARD: number
  XS_DETAIL_ITEM_TYPE_TITLE: number
  XS_DISASTER_DAILY_STATE_NOT_FETCH: number
  XS_PUBLISH_ITEM_TYPE_NOTE: number
  XS_LIMIT_DEFAULT_LV_LOW: number
  get_region_name: function
  XS_DETAIL_ITEM_TYPE_DESC: number
  XS_DETAIL_ITEM_TYPE_COUNT_DOWN: number
  open_manager_window: function
  XS_MANAGER_ACCEPT: number
  get_wuxian_recommend_xiuwei: function
  XS_DEFAULT_NPC_NO: number
  XS_LIMIT_DEFAULT_MEMBER_HIGH: number
  XS_LIMIT_DEFAULT_PERMISSION: boolean
  XS_VIEW_CONTENT_TYPE_WUXIAN: number
  TARGET: number
  get_daily_disaster_xs_state: function
  get_view_filter_list: function
  XS_PUBLISH_ITEM_TYPE_CHECK: number
  XS_LIMIT_DEFAULT_LV_HIGH: number
  XS_PUBLISH_LIMIT_MODE: number
  XS_CHOUSHA_ANIMAL: number
  XS_DETAIL_WINDOW_TYPE_MY_PUBLISH: number
  XS_TAB_MINE_PUBLISH: number
  XS_DAILY_NUM_RATE: number
  XS_HEAD_COLOR_OFFLINE: list
  XS_PUBLISH_REWARD_MODE: number
  (1 more keys)