Module: hexm.common.consts.anim_consts
Type: table
================================================================================

Keys:
  pack_ai_anim_data: function
  THERAPY_ANIM_TYPE_PLAY: number
  ACTION_TRANSIENT_SPEED_MODE_LINEAR: string
  BONE_FILTER_ANIM: string
  ACTION_GROUP_TYPE_FOLLOW: number
  THERAPY_ANIM_TYPE_NONE: number
  BASE_WEAPON_ANIM_PATH: string
  SUFFIX_SLOT_GUISE_TOPS: number
  ACTION_PLAYBACK_SPEED_MODE_PARABOLA: string
  UPPER_FULL_ANIM: string
  get_warmup_weapon_anim_list: function
  ANIM_PATH_CHAR_BODY: dict
  POSE_ANIM_STAGE_LOOP: string
  ACTION_LEAD_FLAG_END: number
  SUFFIX_SLOT_NONE: number
  SYNC_VAR_TYPE_MAP: dict
  FULL_BODY_ANIM: string
  POSE_ANIM_STAGE_IN: string
  POSE_ANIM_STAGE_SUB_IN_BACK_TO_PARENT: string
  ACTION_GROUP_TYPE_LEAD: number
  COMMON_MOTION_GRAPH_PATH: string
  POSE_ANIM_STAGE_SUB_IN: string
  ACTION_TRANSIENT_SPEED_MODE_PARABOLA: string
  POSE_ANIM_STAGE_NONE: string
  ACTION_TRANSIENT_SPEED_MODE_LADDER: string
  ANIM_VAR_IDX: dict
  ACTION_PLAYBACK_SPEED_MODE_LINEAR: string
  SYNC_VAR_TYPE_BASE: number
  POSE_ANIM_STAGE_SUB_OUT: string
  POSE_ANIM_STAGE_SUB_MAIN_OUT: string
  SKILL_STAGGER_ANIM: string
  _reload_all: boolean
  ACTION_GROUP_TYPE_NONE: number
  COMMON_ANIM_GRAPH: string
  ACTION_PLAYBACK_SPEED_MODE_DECAY: string
  FOLLOW_ANIM_TYPE_DEFAULT: number
  SUFFIX_SLOT_MULTI_LANG: number
  unpack_ai_anim_data: function
  pack_anim_vars: function
  FOLLOW_ANIM_TYPE_BUNDLE: number
  ACTION_LEAD_FLAG_BEGIN: number
  unpack_anim_vars: function
  POSE_ANIM_STAGE_OUT: string
  ANIM_SPECIAL_BASE_GRAPH: string
  SUFFIX_SLOT_GUISE_HAIR: number
  SUFFIX_SLOT_SKIN: number
  SUFFIX_SLOT_WEAPON: number
  POSE_ANIM_STAGE_SUB_IN_SAME_MAIN_OLD_OUT: string
  POSE_ANIM_STAGE_SUB_IN_MAIN_IN: string
  ANIM_VARS: list
  (1 more keys)