Module: hexm.common.consts.battle_pass_consts
Type: table
================================================================================

Keys:
  E_BATTLE_PASS_ADD_EXP: number
  E_BATTLE_PASS_CHOICE_REWARD: number
  BP_PRIVILEGE_VIP: number
  BP_TASK_TYPE_WEEK: number
  get_next_season_week_refresh_ts: function
  get_season_open_week_days: function
  get_task_progress: function
  get_need_exp_by_level_gap: function
  BP_PRIVILEGE_FREE: number
  get_is_oversea: function
  E_BATTLE_PASS_TASK_REFRESH: number
  E_BETTLE_PASS_BUY_EXP: number
  get_next_reward_unlock_id: function
  E_BATTLE_PASS_TASK_REWARD: number
  get_current_drug_box_bp_extra_num: function
  get_cur_top_level: function
  BP_NOTIFY_MAIL_LAST_DAYS: number
  E_BATTLE_PASS_CONDITION_CHANGE: number
  get_main_sysd: function
  get_main_sysd_by_id: function
  get_drug_box_bp_extra_num: function
  get_open_week_days: function
  E_BATTLE_PASS_TASK_EXPIRED: number
  _reload_all: boolean
  BP_GROUP_TYPE_NOT_NEWBIE: number
  get_jianfu_bp_exp_ratio: function
  get_diff_weeks_by_season_cycle: function
  get_bp_level: function
  get_bp_exp: function
  get_privilege_sysd: function
  BP_TASK_TYPE_DAY: number
  get_bp_level_by_exp: function
  get_unlock_cond_id: function
  BP_TASK_TYPE_SEASON: number
  E_BATTLE_PASS_PRIVILEGE_BUY_SUCCESS: number
  E_BATTPE_PASS_TASK_DONE: number
  get_last_main_sysd: function
  E_BETTLE_PASS_REWARD: number
  get_next_normal_bp_sysd: function
  get_bp_exp_by_level: function
  BP_PRIVILEGE_VIP_PRO: number
  BP_GROUP_TYPE_NEWBIE: number
  check_battle_pass_unlock: function