Module: hexm.common.consts.build_grid_consts
Type: table
================================================================================

Keys:
  KEY_AREA_DELETE: string
  LOD_LEVEL_1: number
  get_nine_grid_ks: function
  pos_to_grid_k: function
  PUSH_TICK: number
  MAIN_WORLD_TAG: number
  DATABASE_TO_MODEL: dict
  gen_world_gk_id: function
  check_is_grid_space: function
  BPCPP: boolean
  DIS_DATA: number
  KEY_BP_UPDATE: string
  pos_to_grid_idx: function
  LOD_LEVEL_3: number
  BP_COMP_CHANGED_CHECK_KEYS: list
  CHUNK_TYPE_REGION: number
  frea_area_no2pos: function
  DATA_MODEL_BP: string
  chunk_key_to_id: function
  _reload_all: boolean
  LOD_DATA: number
  DATA_MODEL_LAND: string
  LOD_LIST: list
  DIS_ENTITY: number
  FBCPP: boolean
  KEY_FB_DELETE: string
  GRID_CACHE_TIME: number
  DIS_FAR_ENTITY: number
  grid_key_to_center_pos: function
  LOD_FAR_ENTITY: number
  EMPTY_GRID_DATA: dict
  DATABASE_FB: string
  BP_INFO_CHANGED_CHECK_KEYS: list
  get_int_fb_id: function
  M_BP_DATA: string
  GROUP_MODEL_FB: string
  GROUP_MODEL_BP: string
  FB_DIS_LIST: list
  EMPTY_CHUNK_DATA: dict
  is_in_nine_grids: function
  KEY_FB_UPDATE: string
  gen_raw_fb_id_by_pos: function
  grid_key_to_index: function
  is_grid_space: function
  MIN_DS: number
  M_FB_DATA: string
  CHUNK_TYPE_ACTIVITY: number
  GRID_DIS_SIMPLE_BUILD_INIT_RB: number
  GRID_DS: number
  DIS_MAX: number
  (1 more keys)