Module: hexm.common.consts.common_play_consts
Type: table
================================================================================

Keys:
  NO_EXPLORE: number
  NEW_NO_BAIYE: number
  COMMON_STATE_GAME: number
  NEW_NO_DOUDIZHU: number
  COMMON_STATE_END: number
  NEW_NO_POP_CHESS: number
  NEW_NO_HUPAI: number
  NEW_NO_MAJIANG: number
  E_JIGSAW_DONE: string
  gen_prop_key: function
  E_ENTITY_CHECK_CHEAT: string
  NEW_NO_DEBATE: number
  NEW_NO_LANGZHONG: number
  get_next_open_time: function
  NO_ARREST: number
  NEW_NO_DANCE: number
  WANFA_MODULES: dict
  NO_ZHUOYING_XUNQUAN: number
  NEW_NO_ARCHERY: number
  E_ENTITY_LEAVE_SPACE: string
  NO_LANGZHONG_THERAPY: number
  E_ENTITY_ENTER_SPACE: string
  NEW_NO_XIAYUAN_ANS: number
  _reload_all: boolean
  get_next_finish_time: function
  NEW_NO_YEZIXI: number
  STATE_ACTIVE: number
  is_play_index_before: function
  COMMON_STATE_INIT: number
  NEW_NO_DEFAULT: number
  NO_DEFAULT: number
  NO_INDUSTRY_POSTHOUSE_GUESTS: number
  CLIENT_WANFA_MODULES: dict
  ARCHERY_STAGE_INIT: number
  STATE_END: number
  get_wanfa_start_ts: function
  NO_GAME_PRIORITY: dict
  AVATAR_STATE_GAME: number
  is_play_index_open: function
  get_wanfa_season: function
  COMMON_STATE_ON_CREATE: number
  NO_TAVERN_INDUSTRY_BANQUET: number
  ARCHERY_STAGE_END: number
  AVATAR_STATE_LEAVE: number
  ARCHERY_STAGE_STARTED: number
  NO_YEZIXI: number
  ARCHERY_STAGE_PREPARE: number
  NO_DEBATE: number
  NO_NPC_WANFA_BANQUET: number