Module: hexm.common.consts.culture_collection_consts
Type: table
================================================================================

Keys:
  RHYTHM_GAME_START_TYPE_MUL_WORLD: number
  WANFA_SZYY_RHYTHM_GAME_DOUBLE: string
  INTEREST_SKILL_ID: number
  WANFA_SZYY_ADMIRE: string
  RHYTHM_GAME_BEFORE_START_AVT_ERR: string
  get_culture_collection: function
  RHYTHM_GAME_BEFORE_START_VOTE_START: string
  is_instrument_weapon: function
  RHYTHM_GAME_BEFORE_START_FRIEND_ACCEPT: string
  RHYTHM_GAME_BEFORE_START_MATCH_QUIT: string
  WANFA_SZYY_UID: string
  WANFA_SZYY: number
  RHYTHM_GAME_BEFORE_START_ONLY_SINGLE: string
  WANFA_FOLLOW: number
  RHYTHM_GAME_BEFORE_START_BE_INVITED: string
  playing_szyy_ts: function
  RHYTHM_GAME_BEFORE_START_NOT_OWNER: string
  RHYTHM_GAME_START_TYPE_CALL: number
  ALL_WANFA: table
  RHYTHM_GAME_BEFORE_START_WAIT_FRIEND: string
  RHYTHM_GAME_BEFORE_START_CONFIG_ERR: string
  RHYTHM_GAME_PHASE_CHECK: number
  playing_szyy_no: function
  WANFA_SZYY_UNLOCK_MUSIC: string
  RHYTHM_GAME_START_TYPE_MATCH: number
  RHYTHM_GAME_PHASE_READY: number
  has_sizhu_skill: function
  RHYTHM_GAME_PHASE_NOT_READY: number
  RHYTHM_GAME_START_TYPE_ROOM_INVITE: number
  WANFA_SZYY_COLLECTION_REWARD: string
  WANFA_SZYY_RHYTHM_GAME_SINGLE: string
  get_team_members: function
  is_in_szyy_gaming: function
  RHYTHM_GAME_BEFORE_START_NOT_CORP_MODE: string
  is_in_szyy_phase: function
  RHYTHM_GAME_START_TYPE_ONLINE_MATCH: number
  INSTRUMENT_WEAPONS: table
  RHYTHM_GAME_BEFORE_START_MATCH_ERR: string
  RHYTHM_GAME_START_TYPE_SINGLE: number
  RHYTHM_GAME_BEFORE_START_ACCEPT_SUCC: string
  WANFA_MUSICAL_INSTRUMENT_REWARD: string
  WANFA_SZYY_RHYTHM_GAME: string
  is_szyy_point_unlocked: function
  RHYTHM_GAME_START_TYPE_INVITE: number
  RHYTHM_GAME_BEFORE_START_GAME_READY: string
  SZYY_SHARE_ID: number
  RHYTHM_GAME_BEFORE_START_MATCH_SUCCESS: string
  RHYTHM_GAME_PHASE_GAMING: number
  RHYTHM_GAME_BEFORE_START_MATCH_START: string
  RHYTHM_GAME_BEFORE_START_VOTE_FINISH: string
  (1 more keys)