Module: hexm.common.consts.debate_consts
Type: table
================================================================================

Keys:
  BASE_BATTLE_TYPE: number
  E_CHOSE_DECK: string
  BUFF_FUNCS_ADD: dict
  E_PVP_BATTLE_MATCH_CANCEL: string
  E_CHOSE_BATTLE_E: string
  ERR_IS_IN_SILENT: number
  DEBATE_ZHENGFENG: number
  ERR_MATCH_TIME_OUT: number
  STATE_IDLE: number
  ERR_NO_DECK: number
  ST_FIGHTING: number
  ERR_IS_GAME_OVER: number
  FACTION_NPC_CHAT: string
  ERR_NO_REWARD: number
  E_TURN_MSG: string
  TYPE_PLAY: number
  E_INVITE_BATTLE: string
  ERR_LOCK_STUFF: number
  _reload_all: boolean
  ERR_NO_PREPARE_STATE: number
  RANK_DEBATE_SELF2NEED: dict
  TYPE_ANY: number
  BUFF: number
  ST_END_JUDGE: number
  ERR_AI_REPLY_TIMEOUT: number
  E_DEBATE_PREPARE: string
  ERR_CHAT_SENSITIVE: number
  E_UPGRADE_CARD: string
  ERR_BAN_CHAT: number
  E_WHETHER_ACCEPT_BATTLE: string
  BUFF_NAME: dict
  INTEREST_SKILL_ID: number
  E_AI_CHAT_START: string
  E_PRIORITY_INTERRUPT: string
  ERR_CANNOT_AI_DEBATE_COOP_MODE: number
  E_AI_CHAT_END: string
  E_EF_CARD: string
  E_AI_BATTLE_END: string
  ERR_LOCK_XIUWEI: number
  DEBUFF: number
  E_AI_CHAT_OVER: string
  ST_IDLE: number
  ERR_AI_LOCK_RESOURCE: number
  E_PVP_BATTLE_START: string
  ERR_LOCK_POINT: number
  ERR_NOT_CONFIG_DECK: number
  E_CONFIG_CARD_DECK: string
  ERR_CANNOT_UPGRADE: number
  ERR_ADVERSITY_HAS_DO_HS: number
  ERR_NO_ADVERSITY: number
  TYPE_DEBATE: number
  E_PVP_BATTLE_JUDGE_AI: string
  ERR_IS_THIS_DECK: number
  E_MIX_MATCH_RESULT: string
  STATE_READY: number
  E_PVP_BATTLE_REV_MSG: string
  E_START_BATTLE: string
  E_GUIDE_FINISH: string
  E_AI_CHAT_CHAT: string
  ERR_CHAT_TIME_OUT: number
  ROLE2MATCH_RANK: dict
  ERR_CHAT_ERROR: number
  STATE_FIGHTING: number
  E_USE_CARD: string
  ERR_NOT_CAN_QUICK_START: number
  ERR_OP_IN_FIGHT: number
  REPLAY_CODE_TO_ERRCODE: dict
  ERR_AI_TIMEOUT: number
  BUFF_FUNCS_RM: dict
  E_PVP_BATTLE_SEND_MSG: string
  E_PVP_BATTLE_TURN_RESULT: string
  ERR_PLAY_NOT_DEBATE: number
  ERR_OTHER_WANFA: number
  E_QUICK_BATTLE: string
  E_GET_REWARD: string
  E_AI_BATTLE_OVER: string
  ERR_CHAT_BUSY: number
  MATCH_CTRL_RAND: number
  E_AI_BATTLE_CHAT: string
  DEBATE_JIEHUO: number
  E_END_BATTLE: string
  ERR_CHAT_REPLY_WAIT: number
  MATCH_AILAB: number
  E_ABANDON_CARD: string
  MATCH_PVP: number
  E_AI_BATTLE_START: string
  RESPONSE_SENSITIVE: number
  E_PVP_BATTLE_MATCH_TIME_OUT: string
  ST_WAIT_MSG: number
  E_DEBATE_LEAVE: string