Module: hexm.common.consts.disaster_consts
Type: table
================================================================================

Keys:
  STAGE_BOOM: number
  get_disaster_dungeon_robot: function
  get_create_ts: function
  STAR_DISASTER_GP_XS: number
  is_disaster_rescue_space: function
  SCREENSHOT_DUNGEON_END: number
  STAGE_FINISH: number
  get_disaster_dungeon_match_para: function
  DISASTER_MATERIAL_INVITE_REJECT: number
  IDENTITY_BUILD: number
  get_disaster_contribution_value: function
  get_disaster_meteor_visual_param: function
  is_disaster_effect_space: function
  IDENTITY_RESCUE: number
  MAIL_DELAY: number
  UPDATE_RANK_LIST: number
  get_disaster_progress_id: function
  SCREENSHOT_DUNGEON_START: number
  DISASTER_TRIGGER_TIME: number
  get_disaster_meteor_process: function
  get_disaster_meteor_mui_info: function
  STAR_DISASTER_GP_TREASURE_GUARD: number
  get_disaster_stage_remain_time: function
  E_DISASTER_DUNGEON_HAS_OTHER_GANG_MEMBER: number
  IDENTITY_TREATMENT: number
  SCREENSHOT_PUT_OUT_FIRE: number
  STAR_DISASTER_GP_TINAJI: number
  DISASTER_NOTIFY_MSG_ID: string
  check_disaster_dungeon_open: function
  DISASTER_SPACE_CREATE_NUM_MAX: number
  DISASTER_SPACE_CREATE_NUM_MIN: number
  get_disaster_dungeon_npc_team_info: function
  DISASTER_SAVE_MATERIAL_PROC: number
  get_disaster_dungeon: function
  DISASTER_FINISHED_LEVELTO_ICON: dict
  STAR_DISASTER_GP: number
  get_disaster_location: function
  DUMP_DURATION: number
  get_disaster_dungeon_info: function
  E_DISASTER_DUNGEON_WRONG_MEMBER_NUM: number
  SCREENSHOT_MWZX: number
  STAGE_None: number
  is_disaster_dungeon_score_npc: function
  get_disaster_review_data: function
  DISASTER_TYPE_TO_REWARD_IN_GANG_SELF: dict
  OP_ACCEPT: number
  STAGE_DISASTER_GP_JUDIAN: number
  DISASTER_HANDLER_CLZ_MAP: dict
  STAR_DISASTER_GP_DUNGEON: number
  _reload_all: boolean
  (1 more keys)