Module: hexm.common.consts.dungeon_consts
Type: table
================================================================================

Keys:
  get_dungeon_farming_id: function
  STAT_TICK: number
  E_MATCH: string
  E_VOTE_RESULT: string
  CLUB_WEEK_FUBEN_TEAM_TARGET: number
  get_team_dungeon_space_info: function
  get_dungeon_tongyou_id: function
  get_dungeon_unlock: function
  get_dungeon_rank_data: function
  DUNGOEN_TIANJI_REVIVE_DELAY: number
  get_dungeon_tongyou_data: function
  STAT_JIESUAN: number
  get_dungeon_rank_name: function
  REFRESH_WEEKLY: number
  REFRESH_DAILY: number
  E_GET_REWARD: string
  get_dungeon_idx_by_sid: function
  ADDITIONAL_REWARD_TIMES_MAINTAIN_TIME: dict
  DUNGEON_NOT_REWARD: number
  E_START_VOTE: string
  FUBEN_ADDITIONAL_REWARD_TIMES: dict
  E_FORBID: string
  E_ENTER_HALFWAY: string
  get_dungeon_tank_num: function
  get_next_dungeon_spaceno: function
  get_entity_pve_tank_identity: function
  DUNGEON_GIVE_UP: number
  get_dungeon_team_game_id: function
  _reload_all: boolean
  get_dungeon_ai_list: function
  DUNGEON_LEAVE_HALFWAY: number
  E_GAME_PRIORITY: string
  E_DOING_XS: string
  E_LACK_TILI: string
  DUNGEON_FINISH: number
  DUNGEON_BOSS_PASSED: number
  NEWBIE_FINISH_ASPIRATION_ATTR: number
  DUNGEON_BOSS_NOT_PASSED: number
  DUNGEON_REWARD: number
  STAT_DETAIL: number
  get_dungeon_spaceno_by_rank_name: function
  get_dungeon_proceed_by_spaceno: function
  REWARD_ACCUMULATION: number
  dungeon_get_born_pos_and_yaw: function
  get_entity_pve_identity: function
  get_pve_identity_by_wuxue: function
  REFRESH_MONTHLY: number
  get_pre_dungeon_spaceno: function
  is_dungeon_rank_avail: function
  check_is_club_xiajing: function