Module: hexm.common.consts.firework_consts
Type: table
================================================================================

Keys:
  get_firework_aution_sys: function
  STUB_AUTO_AUCTION_FREQ: number
  NAME_COLOR_Y: list
  get_today_firework_info: function
  SOCIAL_GAME_NORMAL_FIREWORK_ID: number
  get_max_auction_uuid: function
  NUM_COLOR_W: list
  get_firework_open_time_range: function
  CUSTOMIZE_DATA_KEY: string
  get_last_auction_uuid: function
  RANK_COLOR_R: list
  FIRE_WORKS_TYPE_5: number
  firework_region_check: function
  get_next_redbag_ts: function
  SPACE_PULL_TS: number
  check_is_customize_firework: function
  AUTO_STOP: number
  get_today_fire_ts_range: function
  FIREWORK_INTERACT_STATUS_STATIC: number
  INVALID_COLOR_R: list
  _reload_all: boolean
  AUTO_AUCTION_RETURN: string
  get_today_newyear_fire_ts_range: function
  FIRE_WORK_PARTY_TYPE_SPRING_FESTIVE: number
  LOCALDB_AUTO_BIDING_RANK_IDX: string
  YAZHOU_RANK: number
  RANDOM_NEAR_ONLINE_PLAYER_TXT: number
  DAKAI_RANK: number
  get_default_customize_info: function
  FIRE_WORKS_TYPE_4: number
  SOCIAL_GAME_NEW_YEAR_FIREWORK_ID: number
  get_bidding_token_icon: function
  get_firework_newyear_plan_sys: function
  auction_in_server_open_data: function
  RANDOM_PLAYER_TXT: number
  SYSTEM_PLAYER_NICKNAME_TXT: number
  biding_precheck: function
  get_today_redbag_start: function
  SA_LOSE_RANK: number
  RANK_COLOR_Y: list
  get_last_firework_open_time_range: function
  get_firework_plan_sys: function
  DAZHOU_RANK: number
  CIKAI_RANK: number
  get_rank_item_style: function
  FIRE_WORK_PARTY_TYPE_NORMAL: number
  SA_BIDING_SUCCESS: number
  UUID_CONF_ID: number
  SA_ERR_DATA: number
  FIRE_WORKS_TYPE_1: number
  (1 more keys)