Module: hexm.common.consts.gang_consts
Type: table
================================================================================

Keys:
  finish_gang_xs: string
  ERR_NO_POST_LEFT: number
  INITIAL_CREATE_JUYITING: string
  ERR_FORBID_APPOINT_THE_AUTH: number
  UNSET_POST_AUTH: number
  GANG_GONGXIAN_OFFSET_MAIL_NO: number
  already_select_area: number
  ERR_EXPIRE_POSTER: number
  ERR_NOT_GANG_XS: number
  DEL_GANG_MOMENT: string
  trigger_next_in_trigger_event: number
  CHANGE_GANG_PURPOSE: string
  ERR_NO_ENOUGH_MONEY_CREATE_GANG: number
  ERR_NOT_MASTER_TAKE_PHOTO: number
  ERR_DISMISS_GANG_IN_ERR_SPACE: number
  GANG_RESIGN: string
  ERR_NOT_SET_GANG_NAME: number
  GANG_TRANSFER: string
  GANG_MEMBERS_SORT_TYPE_POSITION: number
  GET_GANG_WAREHOUSE_DATA: string
  ERR_TRANSFER_TARGET_NOT_IN_GANG: number
  master: number
  gang_warehouse_module: string
  ERR_INVALID_GANG_PHOTO_ID: number
  UPDATE_GANG_AUTH: string
  ERR_IN_GANG_INVITE_CD: number
  gang_post_module: string
  SET_POST_AUTH: number
  ERR_EMPTY_GANG_APPLY_LIST: number
  ERR_INVITED_AVATAR_LOW_LEVEL: number
  CHANGE_GANG_MAIN_PAGE: string
  APPLY_JOIN_GANG_BATCH: string
  AVATAR_ENTER_GANG: string
  ERR_INVALID_GANG_PROP: number
  ERR_CHANGE_GANG_INDUSTRY_NOT_MASTER: number
  ERR_COMMIT_STUFF_FULL: number
  CHANGE_GANG_MAIN_PAGE_BUTTON: string
  GET_DAILY_GANG_GONGXIAN: string
  GANG_MEMBERS_SORT_TYPE_DEFAULT: number
  gang_disaster: string
  SA_LOG_OPTYPE_ENTER: number
  ERR_CREATE_GANG_MEMBER_BEYOND_LIMIT: number
  ERR_GANG_YUNBIAO_DIFF_GANG: number
  gang_collection: string
  ERR_NO_AUTH_OP: number
  gang_construct: number
  CREATE_OR_UPGRADE_GANG_BUILD: string
  ERR_ONLY_GANG_MASTER_CHANGE_GANG_DATA: number
  GET_GANG_LAND_INFO: string
  ERR_CANNOT_UP_INDUS: number
  members_module: string
  DAY_REFRESH: number
  trigger_next_in_finish_event: number
  general_public: number
  create_juyiting: number
  ERR_REACH_LIMIT_IN_TEMP_GANG: number
  DEL_GANG_AUTH: number
  GANG_MEMBERS_FILTER_TYPE_3: number
  ERR_LIMIT_POSITION: number
  USE_GANG_WAREHOUSE_STUFF: string
  ERR_INVALID_GANG_WARE_ID: number
  gang_gongxian_limit_sid: number
  GANG_MEMBERS_SORT_TYPE_XIUWEI_KONGFU: number
  gang_moments_module: string
  CHANGE_GANG_CARD: string
  ERR_NO_LAND_LEFT: number
  ERR_LACK_STUFF: number
  ERR_BEYOND_MAINPAGE_BUTTON_LIMIT: number
  ERR_GANG_MEMBER_REACH_MAX_NUM: number
  GET_GANG_AUTH_DATA: string
  _reload_all: boolean
  ERR_NO_NEED_UNSET_GENERAL_POST: number
  ERR_GET_CUR_STAGE_ACTIVE_REWARD: number
  SEND_GANG_POSTER: string
  GANG_MEMBERS_SORT_TYPE_XIUWEI_TRADE: number
  ERR_SET_TARGET_HIGH_IDENTITY: number
  ERR_NO_CANCEL_PERSISTENT_GANG: number
  ERR_INVITED_AVATAR_NOT_ONLINE: number
  CLEAR_UP_GANG_WAREHOUSE: string
  ERR_LOW_LEVEL_APPLY_FOR_GANG: number
  ERR_IN_TOGETHER_CREATE_GANG_LIST: number
  ERR_NO_AUTH_SET_POST: number
  DEC_GANG_FUND: string
  jingyin: number
  ADD_GANG_FUND: string
  UPDATE_GANG_EVENT: string
  CLICK_POSTER_ACCEPT_INVITE: string
  ERR_SET_POST_TARGET_NOT_IN_THE_GANG: number
  USE_GANG_WAREHOUSE_STUFF_BY_ID: string
  ERR_MUST_NOT_LEAVE_GANG: number
  ERR_GENERAL_NOT_NEED_RESIGN: number
  GET_WEEK_ACTIVE_REWARD: string
  GET_GANG_STUFF_COUNT: string
  ADD_GANG_MOMENT_AUTH: number
  ERR_EMPTY_GANG_PURPOSE: number
  join_gang_activity: string
  GET_GANG_REWARD: string
  GANG_EVENT_INTERACT_TYPE: number
  GANG_CONSTRUCT_COMMIT_STUFF: string
  GANG_KICK_AVATAR_MAIL_NO: number
  ERR_INVALID_GANG_BAG_NO: number
  gang_gongxian_module: string
  INVITE_JOIN_GANG: string
  ERR_INVALID_POSTER_DATA: number
  gang_disaster_module: string
  ERR_INVALID_AUTH_ID: number
  base_module: string
  GANG_MASTER_DISMISS_GANG: string
  SET_POST: string
  GANG_TAKE_PHOTO: string
  ERR_NO_AUTH_UNSET_POST: number
  GANG_MEMBERS_SORT_TYPE_LEVEL: number
  KICK_PERSON: number
  ERR_NO_AUTH_SET_AUTH: number
  recruit_person: number
  CREATE_GANG_TOGETHER: string
  GANG_MEMBERS_SORT_TYPE_TO_PROPERTY: dict
  SA_LOG_OPTYPE_KICK: number
  ERR_ILLEGAL_GANG_MOMENT: number
  GANG_SEARCH_PAGE: number
  ERR_NOT_MASTER_TO_CANCEL_GANG: number
  GANG_EVENT_HANDIN_STUFF_TYPE: number
  ERR_INVALID_POSTER: number
  base_gang_operation: string
  TRIGGER_GANG_EVENT: string
  ERR_INVALID_GANG: number
  ERR_FORBID_CHANGE_GANG_PURPOSE: number
  CONSTRUCT_MANAGE: number
  ERR_EMPTY_GANG_ID: number
  CHANGE_GANG_RESTRICT_XIUWEI: string
  ERR_ALREADY_JOIN_GANG: number
  ERR_ALREADY_SEND_APPLY_REQUEST: number
  GANG_MEMBERS_SORT_TYPE_TIME: number
  GANG_MEMBERS_SORT_TYPE_TO_NAME: dict
  BATCH_RM_STUFF_BY_NO: string
  ERR_CREATE_GANG_LOW_LEVEL: number
  post_map_attr_name: dict
  ERR_KICK_AVATAR_NOT_GANG_MASTER: number
  gang_disaster_wanfa_tag: string
  UPDATE_GANG_INDUSTRY_ID: string
  ERR_OP_AUTH_NOT_GANG_MASTER: number
  ERR_SAME_GANG_INDUSTRY_ID: number
  WEEK_REFRESH: number
  EXCHANGE_GANG_FUND: string
  initial_number_id: number
  GANG_CONSTRUCT: string
  ERR_COMMIT_RES_WRONG_SPACE: number
  GANG_FUND_LACK_MAIL_NO: number
  GET_GANG_EVENTS: string
  ERR_LACK_MONEY_EXCHANGE_GANG_FUND: number
  gang_daily_refresh: string
  ERR_BEYOND_MAINPAGE_PHOTO_LIMIT: number
  ERR_KICKED_AVATAR_NOT_IN_GANG: number
  ERR_APPLICANT_ALREADY_JOIN_GANG: number
  FIRST_SEND_GANG_POSTER: string
  ERR_GANG_BUILD_MUST_IN_GANG_SPACE: number
  BATCH_ADD_STUFF: string
  ERR_COMMIT_NULL_RES: number
  gang_industry_module: string
  query_project_fields: dict
  FIXED_PLANE_GANG_CONFIG_NO: number
  ERR_ILLEGAL_GANG_NAME: number
  ERR_NO_MATCH_GANG_EVENT: number
  ERR_LOW_LEVEL_ENTER_GANG: number
  GANG_MEMBERS_FILTER_TYPE_2: number
  GANG_SPACE_NOS: list
  finish_gang_event: string
  ERR_HAND_IN_STUFF_SHORT: number
  SA_LOG_OPTYPE_LEAVE: number
  GANG_MEMBERS_SORT_TYPE_XIUWEI_EXPLORE: number
  distributed_entity: boolean
  GANG_KICK_AVATAR: string
  ERR_BEYOND_GANG_MOMENTS_LIMIT: number
  ERR_INVALID_APPLY_INFO: number
  ERR_EXCHANGE_FUND_REACH_MAX_MONEY_NUM: number
  persistent_gang: number
  ERR_COMMIT_INVALID_STUFF: number
  cur_not_get_banggong: number
  ERR_ALREADY_GET_GANG_GONGXIAN_CUR_TIME: number
  ERR_MASTER_NOT_NEED_TO_GET_AUTH: number
  GANG_FUND: number
  ERR_EMPTY_GANG_NAME: number
  get_gang_entity_id: function(gang_id)  -- hexm/common/consts/gang_consts.lua:269-271
  ERR_INVITED_ALREADY_IN_GANG: number
  DEAL_WITH_GANG_APPLY: string
  ERR_INVALID_ACTIVE_STAGE_ID: number
  ERR_EXISTS_THE_GANG_NAME: number
  FINISH_GANG_EVENT: string
  DEAL_WITH_GANG_INVITE: string
  ERR_REACH_MAX_GANG_YUNBIAO_NUM: number
  ERR_DISMISS_GANG_NOT_MASTER: number
  HAND_IN_STUFF: string
  gang_disaster_xs: string
  ERR_TARGET_NO_AUTH_GET_GANG: number
  ERR_ILLEGAL_GANG_PURPOSE: number
  ERR_ALREADY_FINISH_GANG_EVENT_TASK: number
  tangzhu: number
  GANG_MEMBERS_SORT_TYPE_CONTRIBUTION: number
  ERR_BEYOND_GANG_WAREHOUSE_LIMIT: number
  gang_industry_col: string
  ERR_NOT_JOIN_GANG: number
  ERR_AUTHED_AVATAR_NOT_IN_GANG: number
  gang_item_module: string
  ERR_NO_AUTH_PUBLISH_XS: number
  ERR_LACK_GANG_FUND: number
  SET_GANG_FENTANG_MASTER: string
  CHANGE_GANG_RESTRICT_LEVEL: string
  ERR_NO_AUTH_FETCH_XS: number
  ERR_GANG_IDENTITY_TO_TRANSFER_GANG: number
  ERR_GANG_ICON_TEXT_LIMIT: number
  ERR_GANG_INVALID_BUILDING: number
  CHOOSE_GANG_MOMENT_PHOTO: string
  RECRUIT_PERSON: number
  TRIGGER_GANG_TAKE_PHOTO: string
  ASSIGN_AUTH: number
  GANG_EVENT_KILL_NPC_TYPE: number
  ERR_GANG_PHOTO_LT_MIN_AVATARS: number
  PLANE_GANG_SPACE_NO: number
  APPLY_JOIN_GANG: string
  CANCEL_CREATE_GANG: string
  GANG_MAP_PAGE: number
  ERR_NO_POWER_KICK_AVATAR: number
  ERR_GANG_YUNBIAO_WRONG_SPACE: number
  GANG_AVATAR_ONLINE: string
  CANCEL_CREATE_GANG_MAIL_NO: number
  COMMON_GANG: number
  ERR_LOW_LEVEL_NOT_APPLY_JOIN_GANG: number
  GANG_MEMBERS_FILTER_TYPE_4: number
  ERR_DISMISS_GANG_ERR_GANG_MEMBER: number
  ERR_NOT_SET_GANG_LAND: number
  CAN_UPGRADE_JUYITING: string
  ADD_GANG_MOMENT: string
  ERR_COMMIT_NUM_LIMIT: number
  cur_get_banggong: number
  ERR_LACK_GANG_CONSTRUCT_DEGREE: number
  never_get_banggong: number
  vice_master: number
  ERR_HAND_IN_MORE_STUFF: number
  GANG_CANCEL_EXPIRE: string
  GANG_GONGXIAN: number
  gang_auth_module: string
  ERR_NO_POWER_DEAL_WITH_APPLY_REQUEST: number
  ERR_NO_AUTH_UNSET_MASTER_POST: number
  ERR_REACH_GANG_XS_PUBLISH_LIMIT: number
  CONSTRUCT_DESIGN: number
  base_module_fields: list
  GANG_ACTIVE_REWARD_MAIL_NO: number
  CREATE_GANG_OVERTIME_MAIL_NO: number
  CHANGE_GANG_ICON: string
  ERR_NOT_SET_SAME_POST: number
  ERR_NO_START_PLANE_GANG: number
  ERR_ALREADY_HAVE_AUTH_ID: number
  ERR_GANG_NO_BUILD_IN_BUILDING: number
  BATCH_RM_STUFF_BY_ID: string
  ERR_ILLEGAL_MONEY_TYPE: number
  ERR_LOW_XIUWEI_APPLY_FOR_GANG: number
  ERR_MUST_NOT_GANG_MASTER_RESIGN: number
  ERR_NOT_HAVE_AUTH_ID: number
  gang_email_reward_no: number
  gang_entity: string
  GET_INVITED_JOIN_GANG: string
  ERR_LOW_BUILDING_LEVEL_PUBLISH_XS: number
  ERR_GET_GANG_GONGXIAN_NOT_IN_GANG: number
  GANG_MEMBERS_FILTER_TYPE_1: number
  ERR_BEYOND_AUTH_NUM_LIMIT: number
  CHANGE_GANG_NAME: string
  PLANE_GANG: number
  ADD_GANG_AUTH: number
  ERR_LOW_ACTIVE_GET_REWARD: number
  ERR_GANG_MASTER_KICK_SELF: number
  ERR_BEYOND_GANG_PHOTO_LIMIT: number
  ERR_CREATE_GANG_LOW_XIUWEI: number
  CREATE_GANG_PERSONAL: string
  GANG_MEMBERS_IDENTITY_TO_NAME: dict
  GANG_AVATAR_OFFLINE: string
  ERR_LOW_LEVEL_TARGET_INVITE_JOIN_GANG: number
  ERR_LOW_XIUWEI_TARGET_INVITE_JOIN_GANG: number
  GANG_EXPIRE: string
  UNSET_POST: string
  AVATAR_LEVEL_GANG: string