Module: hexm.common.consts.graph_consts
Type: table
================================================================================

Keys:
  G_BATTLE_MOTION_TYPE_NORMAL: number
  G_BATTLE_MOTION_TYPE_PRIORITY_MOJIN: number
  G_BATTLE_MOTION_TYPE_PRIORITY_QUICK_RUN: number
  G_BATTLE_MOTION_TYPE_DEFENCE: number
  VARIABLE_TYPE_STR: number
  G_BATTLE_MOTION_TYPE_PRIORITY_THROW_MODE: number
  G_BATTLE_MOTION_TYPE_LOCK: number
  G_BATTLE_MOTION_TYPE_PRIORITY_ARCHER_MODE: number
  G_BATTLE_MOTION_TYPE_PRIORITY_MOVABLE_SKILL: number
  G_BATTLE_MODE_NO_BATTLE: number
  VARIABLE_TYPE_BOOL: number
  VARIABLE_TYPE_V3LIST: number
  G_BATTLE_MOTION_TYPE_PRIORITY_SKILL_ARCHER: number
  VARIABLE_GET_FUNC_MAP: dict
  VARIABLE_TYPE_INT: number
  G_BATTLE_MOTION_TYPE_PRIORITY_LOCK_MOVE: number
  G_BATTLE_MOTION_TYPE_ARCHER: number
  G_BATTLE_MOTION_TYPE_THROW: number
  VARIABLE_TYPE_MATRIX: number
  VARIABLE_TYPE_FLOAT: number
  G_BATTLE_MODE_IN_BATTLE: number
  VARIABLE_TYPE_CONVERTER: dict
  G_BATTLE_MOTION_TYPE_PRIORITY_DEFENCE: number
  VARIABLE_TYPE_VECTOR3: number
  G_BATTLE_MOTION_TYPE_TELEKINESIS: number
  G_BATTLE_MOTION_TYPE_MOJIN: number
  transfer_value_str: function
  pre_process_value: function
  VARIABLE_SET_FUNC_MAP: dict
  VARIABLE_TYPE_FLOATLIST: number