Module: hexm.common.consts.hangdang_gouzai_consts
Type: table
================================================================================

Keys:
  ERR_BEYOND_THE_UPGRADE_SKILL: number
  ERR_NO_PAINT: number
  dec_attr_skill: number
  xue_zhai_lei_lei: number
  combat_leave: number
  jimou_consume_inc_skill: number
  ERR_AVATAR_HAVE_CLUE_GROUP_ID: number
  immune_damage_skill: number
  ERR_LOW_LEVEL_AUTO_GET_CLUE: number
  dec_jimou_support_effective: number
  negative_zhuoying_xs: number
  magic_damage: number
  ERR_AVATAR_NO_TASK: number
  ERR_NOT_IN_EFFECTIVE_MAP: number
  ERR_HAVE_LOCK_SKILL: number
  ERR_NO_ENOUGH_JIMOU_RESOURCE: number
  ERR_FORBID_LEAVE_JAIL: number
  ERR_LEVEL_NOT_REQUERE: number
  trigger_arrest: number
  to_enemy: number
  ERR_NO_CONTENT_IN_SHEET: number
  ERR_NO_ENOUGH_YIXIN_RESOURCE: number
  ERR_NEAR_END_POINT: number
  ERR_LACK_STUFF_UNLOCK_SKILL: number
  lan_sha_wu_gu: number
  ERR_LACK_STUFF_UPGRADE_SKILL: number
  trap_type: number
  attr_cause_hp_inc: number
  avatar_first_send_card: number
  change_value_skill: number
  add_attr_skill: number
  dialog_clue_type: number
  ERR_NO_CARDS: number
  ERR_NPC_NO_PAINT_CLUE_ID: number
  ERR_FORBID_SKILL: number
  attr_cause_hp_dec: number
  ERR_TRIGGER_EVENTS_TIMES_LIMIT: number
  apply_immediate: list
  first_send_card_skill_buff_id: number
  ERR_NOT_UNLOCK_THE_SKILL: number
  ERR_NO_GENZONG: number
  send_card_in_sequence: number
  physics_damage: number
  ERR_NO_SEND_CARD: number
  change_attr_skill: list
  an_jian_shang_ren: number
  ERR_IDENTITY_GRADE_AUTO_GET_CLUE: number
  ERR_LOW_LEVEL_UNLOCK_SKILL: number
  ERR_MUST_NOT_APPLY_SKILL: number
  buff_type: number
  ERR_TRIGGER_EVENTS_TIME_LIMIT: number
  ERR_ZHUOYING_AUTO_DEBATE: number
  change_support_rate: number
  ERR_ALREADY_IN_PAINT_WANFA: number
  evidence_clue_type: number
  hangdang_genzong_inner: number
  npc_win: number
  hangdang_zhuizong_success: number
  ERR_SKILL_LEVEL_REACH_MAX_LEVEL: number
  ban_jimou_value_skill: number
  hangdang_genzong_middle: number
  hangdang_genzong_outer: number
  ERR_SELECT_CLUE_NUM_NOT_MEET: number
  after_jiesuan: number
  remove_skill: number
  skip_round_skill_buff_id: number
  _reload_all: boolean
  ERR_NPC_NO_JOB: number
  dec_support_skill: number
  ERR_NOT_AUTO_GET_CLUE: number
  look_trap_skill: number
  ERR_INITIAL_SKILL_LV: number
  suspect_resource: string
  hangdang_zhuizong_fail: number
  ERR_FAR_GENGZONG_NPC: number
  paint_clue_type: number
  ERR_IDENTITY_NOT_MEET: number
  avatar_win: number
  ERR_ALREADY_IN_ZHUIZONG_WANFA: number
  yu_rou_bai_xing: number
  ERR_OK: number
  ERR_FORBID_CARD_TYPE: number
  ERR_NOT_REACH_AUTO_GET_CLUE_TIME: number
  ERR_CARRY_LOW_LEVEL_SKILL: number
  positive_zhuoying_xs: number
  change_space_leave: number
  ERR_BEYOND_DEBATE_TIMES: number
  start_arrest: number
  ERR_INVALID_SKILL: number
  default: number
  debuff_type: number
  hangdang_zhuoying_id: number
  before_jiesuan: number
  ERR_NO_SHEET_DATA: number
  ERR_SPACE: number
  ban_apply_skill: number
  ERR_ALREADY_UNLOCK_THE_SKILL: number
  forbid_play_card_skill: number
  ERR_NO_DEBATE_TOPIC: number
  ERR_NO_SELECT_CARD: number
  ERR_LOW_LEVEL_UPGRADE_SKILL: number
  ERR_LAOD_SKILL_SLOT_ERROR: number
  initial_skill_lv: number
  word_flip_skill: number
  ERR_MULTI_CLICK_START_DEBATE: number
  ERR_ALREADY_AUTO_GET_CLUE: number
  ERR_DEBATE_END: number
  ERR_NO_MILING_ID: number
  apply_delay: list
  ERR_NO_ZHUIZONG_ROUTE: number
  ERR_CARD_NOT_IN_CUR_MILING: number
  to_other: number
  ERR_NPC_NO_TASK: number
  npc_first_send_card: number
  ERR_NOT_ENOUGH_MONEY_LEAVE_JAIL: number
  _end: number
  ERR_NEAR_GENZONG_NPC: number
  to_self: number
  ERR_FORBID_GET_MORE_CLUE: number
  ERR_ALREADY_IN_GENZNG_WANFA: number
  pause: number
  ERR_ALREADY_UPGRADE_THE_SKILL: number
  ERR_NOT_IN_SELF_ROUND: number
  enter: number
  ban_simple_attack: number
  ERR_BEYOND_MAX_CLUE_NUM: number
  ERR_AUTO_GET_CLUE_COUNT_LIMIT: number
  start: number
  ERR_NOT_FIND_NPC: number
  send_card_random: number
  ERR_NO_SHEET: number