Module: hexm.common.consts.identity_pvp_consts
Type: table
================================================================================

Keys:
  MEMBER_CHOOSE_IDENTITY_OR_PREPARE: number
  PVP_NOTIFY_EVENT_LANGZHONG_MEDICINE_ON_SALE: number
  PVP_LANGZHONG_TOKEN_TYPE: number
  is_identity_langzhong: function
  get_pvp_identity: function
  PVP_NOTIFY_EVENT_WUDAO_BE_HIT_2: number
  PVP_NOTIFY_EVENT_LANGZHONG_THERAPY: number
  CHANGE_STATE: number
  REMOVE_STAGE: number
  CHOOSE_IDENTITY: number
  RECEIVE_APPLY_WUDAO: number
  WUDAO_CHANGE: number
  VOTE_RESULT: number
  PVP_BATTLE_LEAVE_SPACE_STATE_HALFWAY: number
  PVP_JIESUAN_ONE_ROUND_END: number
  get_identity_pvp_doctor_medicine_price: function
  WUDAO_KEY: string
  PVP_JIESUAN_FINAL: number
  _reload_all: boolean
  PVP_WUDAO: number
  is_identity_anying: function
  BAIYE: number
  LANGZHONG_LEAVE: number
  is_middle_camp: function
  PREPARE_MATCH: number
  get_team_wudao_pid: function
  E_ROLE_PREPARED: string
  get_pvp_identity_text: function
  LAUNCH_VOTE: number
  DEAL_APPLY_WUDAO: number
  E_INIT_PVP_SPACE: string
  PVP_LANGZHONG: number
  is_identity_wudao: function
  ADD_STAGE: number
  BATTLE: number
  E_WUDAO_ONE_ROUND_END: string
  CHOOSE_MAP: number
  WUDAO: number
  PVP_BUKUAI: number
  BEFORE: number
  PVP_BATTLE_LEAVE_SPACE_STATE_NORMAL: number
  PVP_BAIYES: list
  PVP_NOTIFY_EVENT_WUDAO_BE_HIT_3: number
  CHANGE_POS: number
  WUDAO_LEAVE: number
  PVP_JIANGREN: number
  WUDAO_ATTEND: number
  E_WUDAO_ONE_BATTLE_END: string
  PVP_BUFENG: number
  APPLY_WUDAO: number
  (1 more keys)