Module: hexm.common.consts.instrument_consts
Type: table
================================================================================

Keys:
  BLACKOUT_STAY_TIME: number
  SETTING_SHOW_AVT: string
  MODE_TYPE_FREE_PLAY: number
  get_note_img_name: function
  get_extra_score_by_admire: function
  SETTING_SOUND_SYNC_OTHERS: string
  get_song_stuffs: function
  check_is_follow_leader: function
  get_note_text: function
  UPLOAD_NOTE_NUM_LIMIT: number
  PLAYER_OTHER_KEY_LIMIT_COUNT: number
  SAVE_CD: number
  SAVE_MODE_SERVER: number
  SAVE_MODE_TEMP: number
  INSTRUMENT_STATE_RESULT_PRISON: number
  MODE_RECORD: number
  SZYY_MODE_DOUBLE: number
  INSTRUMENT_STATE_FREE_PLAY: number
  E_CHANGE_HALF_KEY_ENABLE: string
  get_custom_song_stuff_no: function
  get_column_idx: function
  PLAYER_KEY_LIMIT_COUNT: number
  is_classic_note_forbidden: function
  NOTE_MODE_CLASSIC: number
  check_instrument_ground_height: function
  INSTRUMENT_GUZHENG: number
  FREE_CAM_JOYSTICK_SPEED: number
  MUSIC_TYPE_FOLLOW: number
  HALF_NOTE_UPPER: list
  MODE_FOLLOW: number
  INSTRUMENT_STATE_WATING: number
  get_showing_anim_actions: function
  SETTING_FREE_CAMERA: string
  get_active_instrument_entry_nos: function
  ASYNC_BUFFER_TIME: number
  PLAYER_SINGLE_KEY_LIMIT: number
  SAVE_MODE_LOCAL_DB: number
  SETTING_SHOW_TEAMMATE: string
  get_column_idx_without_half_note: function
  get_natural_or_half_index: function
  SZYY_MODE_SINGLE: number
  get_half_note_column_idx: function
  get_keyboard_id_by_origin_idx: function
  E_CHANGE_LINE_ENABLE: string
  MODE_TYPE_FOLLOW: number
  FREE_CAM_DISABLE: number
  SETTING_KEYBOARD_MODE: string
  HALF_NOTE_IDX: list
  HALF_NOTE_COUNT: number
  CUSTOM_SONG_STUFF_SUBTYPE: number
  (1 more keys)