Module: hexm.common.consts.majiang_consts
Type: table
================================================================================

Keys:
  E_SET_SINGLE_FAN: number
  TIMEOUT_PLAY_CARD: string
  get_card_weight: function(cards)  -- hexm/common/consts/majiang_consts.lua:73-110
  END_TYPE_NO_REMAIN: string
  END_TYPE_HU_SANJIA: string
  E_INVITE_NPC: number
  ACK_PENG: string
  MAJIANG_TRAP_NO: number
  R_LEAVE_GAME: number
  E_BE_URGE: number
  ACK_GUO: string
  R_ROOMER_KICK: number
  CARD_WAN: number
  majiang_is_skip_process: function(desk_sid)  -- hexm/common/consts/majiang_consts.lua:355-363
  GANG_TYPE_ZHI: number
  STATE_IN: number
  E_LEAVE_GAME: number
  R_CAN_NOT_FIND: number
  FAN_TYPE_ZIMO: number
  FAN_TYPE_QINGYISE: number
  MAJIANG_LOG_OP: table
  R_LACK_BEAN: number
  STATE_PREPARED: number
  OP_PLAY_CARD: number
  get_card_type: function(card_num)  -- hexm/common/consts/majiang_consts.lua:69-71
  R_LOGIN: number
  LeftSideNeighborCards: list
  majiang_is_pve: function(desk_sid)  -- hexm/common/consts/majiang_consts.lua:351-353
  E_PLAY_CARD: number
  MAJIANG_PAIWEI_ACTIVITY_NAME: string
  MAX_MAJIANG_CREATE_WAIT_TIME: number
  FAN_TYPE_JIANG_QIDUI: number
  MAJIANG_MULTI_EVENT_ID: number
  FAN_TYPE_DUANYAOJIU: number
  MAJIANG_PAIWEI_PREPAI_AGAIN: number
  E_LACK_PREFIX: number
  GAME_STATE_PREPARE: number
  SideCards: list
  E_ASK_QIANGGANGHU: number
  E_JOIN_GUANZHAN: number
  FAN_TYPE_PENGPENGHU: number
  TURN_STATE_WAIT_PLAY: number
  MAJIANG_PAIWEI_MAX_INTERVAL: number
  E_KICK: number
  FAN_TYPE_QIANGGANGHU: number
  majiang_all_desk_sid_list: function(majiang_point_id)  -- hexm/common/consts/majiang_consts.lua:376-380
  E_UNPREPARE: number
  DOT: list
  LeftSideCards: list
  E_ACK: number
  majiang_is_dog: function(avatar)  -- hexm/common/consts/majiang_consts.lua:365-374
  E_GANG: number
  E_JIESUAN: number
  ACK_GANG: string
  FAN_TYPE_JIANG_SHUANGLONG_QIDUI: number
  E_RESTART: number
  E_NEXT_TURN: number
  MAX_MAJIANG_WEEK_RECORD_NUM: number
  STATE_IDLE: number
  END_TYPE_NO_PLAYER: string
  R_LOSE_CLIENT: number
  OP_GANG: number
  BAM: list
  E_SIT_DOWN_CHECK: number
  E_PENG: number
  E_ASK_HU_PENG: number
  FAN_TYPE_DIHU: number
  SideNeighborCards: list
  _reload_all: boolean
  FAN_TYPE_JIANG_SANLONG_QIDUI: number
  E_HU: number
  E_GET_RECORD_HISTROY: number
  MAJIANG_INVITE_REFUSE: number
  R_OWNER_LEAVE: number
  R_FAILED: number
  E_LOSE: number
  CARD_BAM: number
  All_Distinct_Card: list
  NO_JIESUAN_STATE: list
  E_PLAYER_ADD: number
  E_BEAN_NUM_CHANGE: number
  GANG_TYPE_JIA: number
  OP_HU: number
  GAME_STATE_JIESUAN: number
  FAN_TYPE_YAOJIU: number
  TURN_STATE_IDLE: number
  STATE_HU: number
  E_CHA_DAJIAO: number
  FAN_TYPE_TIANHU: number
  CARD_DOT: number
  R_ROOM_DESTROY: number
  E_HU_OTHER: number
  STATE_LOSE: number
  GANG_TYPE_AN: number
  get_majiang_point_by_desk_sid: function(desk_sid)  -- hexm/common/consts/majiang_consts.lua:341-349
  R_TRANSFER: number
  FAN_TYPE_LONG_QIDUI: number
  E_REFRESH_CARDS: number
  TIMEOUT_ACK: string
  R_LEAVE_ROOM: number
  FAN_TYPE_SANLONG_QIDUI: number
  E_CHA_HUAZHU: number
  WAN: list
  FAN_TYPE_PING: number
  R_CRASH: number
  GAME_STATE_PLAY: number
  E_TUISHUI: number
  FAN_TYPE_JINDIAODIAO: number
  RightSideNeighborCards: list
  R_CLIENT: number
  FAN_TYPE_JIANG_DUI: number
  FAN_TYPE_QIDUI: number
  TOY_DESK: number
  CARD_TABLE: dict
  E_PREPARE: number
  HOMEWORLD_DESK: number
  FAN_TYPE_SHUANGLONG_QIDUI: number
  FAN_TYPE_SHIBALUOHAN: number
  R_LEAVE_SPACE: number
  E_GET_SPECATOR_INFO: number
  FAN_TYPE_HAIDILAOYUE: number
  R_LOSE_GAME: number
  FAN_TYPE_GEN: number
  FAN_TYPE_GANGSHANGKAIHUA: number
  R_UNKOWN: number
  R_GAME_PRIORITY: number
  E_PLAYER_LEAVE: number
  get_self_and_neighbor_cards: function(cards)  -- hexm/common/consts/majiang_consts.lua:47-67
  RightSideCards: list
  MAJIANG_INVITE_AGREE: number
  R_DEAD: number
  E_LACK_END: number
  ACK_HU: string
  E_ASSIGN: number