Module: hexm.common.consts.match_consts
Type: table
================================================================================

Keys:
  is_pvp_match: function
  VOTE_MANAGER_STATE_VOTING: number
  RULE_20: number
  TEAM_TARGET_CHIJI_5: number
  need_loading: function
  VOTE_MANAGER_EVENT_VOTE_FAILED: number
  AI_MATCH_AI: string
  MULTI_WANFA_TYPE_FUBEN: number
  MATCH_LUNJIAN2V2: number
  VOTE_MANAGER_STATE_IDLE: number
  MATCH_INVITE_PITCH_POT: number
  MODE_ROOM: number
  RULE_12: number
  E_MATCH_MERGE_TEAM_CONFIRM: number
  PVP_UI_ID_chiji_double: number
  VOTE_CHOICE_CONFIRM: number
  get_match_control_dict: function
  MATCH_INVITE_SUMO: number
  MATCH_LUNJIAN: number
  match_interrupt_type_gather_point: number
  RULE_17: number
  MATCH_CHIJI_1: number
  MATCH_INVITE_WANFA_PLAY_CHECK_FUNC: dict
  MULTI_WANFA_TYPE_COMMON: number
  VOTE_TYPE_DUNGEON_ACTOR: number
  VOTE_MANAGER_EVENT_START: number
  multi_match_get_point_by_social_point: function
  MATCH_XS_TONGYOU_FINISH: dict
  MATCH_INVITE_POSITION_FUNC: dict
  VOTE_CHOICE_NONE: number
  match_multi_check: dict
  MATCH_CHIJI_5: number
  _is_least_duty_match: function
  MATCH_TOUCH_GOLD_REWARD: number
  multi_match_get_point: function
  match_multi_interrupt: dict
  MULTI_WANFA_TYPE_MULTIEVENT: number
  ONLINE_ROOM_TEAM_TARGET_ID: number
  E_BACK_CONFIRM: number
  MATCH_INVITE_PITCH_POT_TOY: number
  E_ENTER_TEAM: string
  VOTE_FROM_MATCH: string
  match_id_to_check_condition: dict
  E_MATCH: number
  TEAM_TARGET_MULTI_MWZX: number
  MATCH_VOTE_DUNGEON_ACTOR_TIME: number
  MATCH_DUNGEON: number
  remove_check: dict
  DOUDIZHU_3: number
  MATCH_LUNJIAN3V3: number
  (1 more keys)