Module: hexm.common.consts.newspaper_consts
Type: table
================================================================================

Keys:
  get_informer_game_refresh_ts: function
  INTERACTION_TYPE_QA: number
  get_status_by_post_data: function
  POST_TAG_STATUS_POST_GLOBAL: number
  has_in_tianxia_at: function
  POST_TAG_STATUS_RECOMMENDING: number
  POST_TAG_STATUS_POST_FRIEND: number
  is_guide_task_completed: function
  RICH_COLOR_RED: list
  is_informer_huiyi_unlock: function
  OPERATION_MODE_RECOMMEND: number
  OPERATION_MODE_REVIEW: number
  NEWSPAPER_FUNCTION_ON: boolean
  NEWSPAPER_TYPE_TOUGAO: number
  POST_TAG_STATUS_REVERTING: number
  NEWSPAPER_TYPE_YUSHE: number
  get_fengmei_level: function
  POST_TAG_DEFAULT: string
  NEWSPAPER_COMMERCIAL_REC_NONE: number
  LOCAL_DB_STAT_POST_CNT: string
  NEWSPAPER_COMMERCIAL_REC_GUARANTEE: number
  get_interaction_info_by_ts: function
  is_status_posted: function
  POST_TAG_STATUS_REVERTED: number
  DISAGREE_BY_OTHER_ZHY: number
  LOCAL_DB_STAT_POST_STATUS: string
  NEWSPAPER_TYPE_SHENGCHENG: number
  get_fengmei_score: function
  check_goods_time_valid: function
  get_baodi_chatroom_id: function
  CONTRIBUTE_STATUS_REVIEW: number
  OPERATION_MODE_VIEW: number
  NEWSPAPER_LOCALDB_OPERATED_POSTS: string
  has_in_tianxia: function
  POST_STATUS_DISPLAY_ITEMS: list
  get_interaction_type_by_type: function
  DAILY_LIMITED_MSG: number
  post_history_sort_like_higher: function
  get_fengmei_red_point: function
  NEWSPAPER_SECTIONS: list
  NEWSPAPER_SECTION_TIANXIA: number
  NEWSPAPER_TYPE_HUIYI: number
  MAX_CONTRIBUTE_NEWS_KEEP: number
  OPERATION_MODE_REVERT: number
  POST_TAG_STATUS_VERIFIED: number
  RICH_COLOR_GREEN: list
  OPERATION_MODE_ATED: number
  RICH_COLOR_YELLOW: list
  get_first_daily_news_id: function
  RICH_COLOR_NOR: list
  (1 more keys)