Module: hexm.common.consts.online_recommendation_consts
Type: table
================================================================================

Keys:
  ERR_PEOPLE_NOT_ENOUGH: number
  COOP_MATCH_TYPE_MAIN: string
  SOCIAL_RECOMM_SCENE_TYPE_2_RECOMMEND_TYPE: table <UnknownInstance>
  MATCH_TYPE_LEADER: number
  MATCH_STATE_MATCH_CONFIRM: number
  SOCIAL_RECOMM_SCENE_TYPE_SHADOW: number
  ERR_HAS_TAG_ERROR: number
  SOCIAL_RECOMM_SCENE_TYPE_ONLINE: number
  CONFIRM_STATE_MEMBER_REJECT_NOTIFY: number
  SOCIAL_RECOMM_GAMEID: string
  SOCIAL_RECOMM_SCENE_TYPE_FRIEND: number
  ERR_FORMAT_INVALID: number
  SOCIAL_RECOMM_SERVER_URL_TEST_IN: string
  MATCH_STATE_MATCH_WAIT_LEADER: number
  MATCH_STATE_MATCHING: number
  MATCH_SOURCE_OTHER: number
  SOCIAL_RECOMM_SERVER_URL_TEST: string
  COOP_MATCH_TYPE_TIANYAKE: string
  COOP_MATCH_TYPE_SIDEPAGE: string
  ERR_RETURN_TIMEOUT: number
  SOCIAL_RECOMM_RECOMMENDATION_PATH: string
  RECOMMEND_TYPE_2_SOCIAL_RECOMM_SCENE_TYPE: table <UnknownInstance>
  _reload_all: boolean
  MATCH_SOURCE_TIANYAKE: number
  WAITING_TYPE_TIMEOUT: number
  ERR_NOT_USE_UX: number
  MATCH_STATE_PADDING: number
  CONFIRM_STATE_WAIT_LEADER: number
  get_position_region_info: function(avt)  -- hexm/common/consts/online_recommendation_consts.lua:40-59
  CONFIRM_STATE_LEADER_REJECT: number
  SOCIAL_RECOMM_SERVER_URL_NORMAL: string
  SOCIAL_RECOMM_TOKEN: string
  SOCIAL_RECOMM_SCENE_TYPE_TEAM: number
  SOCIAL_RECOMM_FAST_REQUEST_TIMEOUT: number
  MATCH_TYPE_MEMBER: number
  CONFIRM_STATE_NO_CONFIRM: number
  WAITING_TYPE_NO_LEADER: number
  MATCH_SOURCE_POST: number
  WAITING_TYPE_HAS_LEADER: number
  CONFIRM_STATE_REJECT: number
  CONFIRM_STATE_DONE: number
  SOCIAL_RECOMM_ORDERID: string
  MATCH_SOURCE_REGION: number
  ERR_NOT_SATISFY_USE_SCENE: number