Module: hexm.common.consts.painting_boat_consts
Type: table
================================================================================

Keys:
  UWSGI_PAINTING_BOAT_BUILD_DATA_SET_PROGRESS: string
  DB_LOAD_NUM_ONCE: number
  UWSGI_RANDOM_GET_BUILD_DATA_NUM: number
  PAINTING_BOAT_SMALL_GAME_FISHING: number
  PAINTING_BOAT_RIVER_SIGHTSEEING_TYPE_PUBLIC: number
  UWSGI_DEL_BUILD_SPACE_INFO: string
  UWSGI_SET_RIVER_SIGHTSEEING_DATA: string
  PAINTING_BOAT_SMALL_GAME_SWING: number
  PAINTING_BOAT_SMALL_GAME_MAJIANG: number
  UWSGI_PAINTING_BOAT_BUILD_SPACE_SYNC_DATA: string
  SPACE_TYPE_UNKNOWN: number
  PAINTING_BOAT_SMALL_GAME_EMPTY: string
  get_painting_boat_trans_config_no: function(avatar, space_no)  -- hexm/common/consts/painting_boat_consts.lua:75-86
  PAINTING_BOAT_SMALL_GAME_SUMO: number
  UWSGI_PAINTING_BOAT_RANDOM_GET_BUILD_DATA: string
  UWSGI_GET_AND_CHECK_RIVER_SIGHTSEEING_DATA: string
  UWSGI_UPLOAD_PAINTING_BOAT_POS: string
  UWSGI_GET_RIVER_SIGHTSEEING_DATA: string
  PAINTING_BOAT_RIVER_SIGHTSEEING_TYPE_REQUEST: number
  PAINTING_BOAT_SMALL_GAME_FIREWORK: number
  UWSGI_EDIT_RIVER_SIGHTSEEING_INFO: string
  SPACE_TYPE_FREE_PARTY: number
  PAINTING_BOAT_SMALL_GAME_PERFORM: number
  PAINTING_BOAT_SMALL_GAME_YEZIXI: number
  OP_REJECT: number
  SMALL_GAME_ERR_CODE_CHANGE: dict
  PAINTING_BOAT_RIVER_SIGHTSEEING_TYPE_PRIVATE: number
  PAINTING_BOAT_STATUS_WAIT_R_S: number
  UWSGI_PAINTING_BOAT_GET_BUILD_DATA: string
  SPACE_TYPE_BUILD: number
  PAINTING_BOAT_RIVER_SIGHTSEEING_TRAP_SERIAL_ID: number
  _reload_all: boolean
  UWSGI_PAINTING_BOAT_BUILD_GET_SEAT: string
  SMALL_GAME_NEED_CLEAR_RELATION: dict
  UWSGI_CHECK_RIVER_SIGHTSEEING_PERMISSION: string
  get_build_trans_config_no: function(avatar, owner_id)  -- hexm/common/consts/painting_boat_consts.lua:88-108
  UWSGI_PAINTING_BOAT_SET_BUILD_DATA: string
  SPACE_TYPE_RIVER_SIGHTSEEING: number
  PAINTING_BOAT_SMALL_GAME_BENCH: number
  get_p_b_f_p_trans_config_no: function(space_no)  -- hexm/common/consts/painting_boat_consts.lua:68-73
  PAINTING_BOAT_SMALL_GAME_FENWEI: string
  PAINTING_BOAT_NOT_INIT_TAG: dict
  OP_ACCEPT: number
  PAINTING_BOAT_SMALL_GAME_ARCHERY: number
  UWSGI_PAINTING_BOAT_BUILDS_CHECK_STATUS: string
  PAINTING_BOAT_STATUS_NORMAL: number
  PAINTING_BOAT_STATUS_RS: number
  BOAT_RED_POINT_HUD: string
  UWSGI_PAINTING_BOAT_BUILD_DATA_FINISH: string
  PAINTING_BOAT_SMALL_GAME_BIRD_KEY: string
  PAINTING_BOAT_SMALL_GAME_FIREWORK_OPEN: string