Module: hexm.common.consts.priority_consts
Type: table
================================================================================

Keys:
  FREE_MUSIC: number
  DISASTER_DUNGEON: number
  POLICE: number
  CHIJI_BETRAYER: number
  ARENA: number
  TANSUODU_XS: number
  JRFQ: number
  DUNGEON: number
  LUNJIAN_3V3: number
  APPLY_COOP: number
  NPC_STUFF: number
  HORSE_FOLLOW: number
  ANIM_ACTION: number
  PUMAI: number
  PBW: number
  TOWER_SYS: number
  DIELUOHAN: number
  INTERRUPT_LOGOUT: number
  FISHING_CONTEST_PVP: number
  INVITE_COOP: number
  CHESS: number
  JIEYU: number
  BREAK_SELF: number
  RECALL_SHILIAN: number
  FENBAO_QINGHE: number
  RIDING_TOGETHER: number
  JL_GY: number
  COMMON_MATCH: number
  SNZD: number
  CATCH_HORSE: number
  DOUDIZHU: number
  CONVERT_BODY_TYPE: number
  JL_ZHY: number
  XIAYUAN_ANS: number
  AUTO_NAVIGATE: number
  RULE_HS_JZ: number
  BATTLE_GUIDE: number
  FOLK_SUMO: number
  HORSE_DRAWN: number
  CARD_COMPETITION: number
  ZUOZHEN: number
  ORDER_CHALLENGE: number
  DRAGON_ARENA: number
  LUNJIAN_2V2: number
  ORDER_SUIXING: number
  PORRIDGE: number
  BOSS_TRAIN: number
  MATERIAL_PROC: number
  PRISON_YOUJIE: number
  SHEFU: number
  SINGLE_PVE_BATTLE: number
  ORDER_YINGCI: number
  FOLK_FLYING: number
  DISASTER_RESCUE: number
  SCHOOL_LEARN: number
  WORLD_LEVEL_DUNGEON: number
  DISASTER_MATERIAL_SHOOT: number
  SPECIAL_TRAINING: number
  JL_TQ: number
  JLM_RULE: number
  DUNGEON_MATCH: number
  GUILD_ELECT: number
  ROOM_JUDIAN: number
  _reload_all: boolean
  RHYTHM_FOLLOW: number
  SZYY: number
  PRISON: number
  ORDER_MONK: number
  YUNBIAO: number
  CLUB_TRANSFER: number
  CHIJI_SINGLE: number
  DISASTER_MATERIAL_PROC: number
  GRANNY_RACE: number
  INTERRUPT_TRANSFER: number
  PVPSJ: number
  JL_JLM: number
  PRIORITY_CANCEL: dict
  HUIWU: number
  BREAK_NONE: number
  INTERRUPT_BEHIT: number
  LUNJIAN: number
  MAJIANG: number
  NO_STORY_ACT: number
  BREAK_TARGET: number
  INTERRUPT_IS_CLIENT: dict
  FOLK_HUPAI: number
  FEITIANWU: number
  SCHOOL_STEAL_LEARN: number
  MULTI_MWZX: number
  ORDER_HELL: number
  SMALL_ZAOTANG: number
  CHIJI_TEAM: number
  MOJIN: number
  ORDER_CHASE: number
  NO_TREASURE_GUARD: number
  ONLINE_MATCH: number
  PINJIU: number
  ORDER_DUNGEON: number
  CLUB_PK: number
  WJJL: number
  LM_INN_NIGHT: number
  CLUB_ANBAO: number
  LZ_THERAPY: number
  WENSHI_MULTI_ANSWER: number
  INTERRUPT_PRIORITY: number
  MULTI_THERAPY_EVENT: number
  LUANDOU: number
  GATHER_WANFA: number
  LM_AI_BATTLE: number
  HORSE_CARRY_ARREST: number
  WFBR: number
  GUILD_SEASON: number
  PITCH_POT: number
  INTERRUPT_DIANXUE: number
  INTERRUPT_RECONN: number
  HUASHU: number
  RECALL_JUQING: number
  DANCE: number
  TREASURE_GUARD: number
  NO_JUDIAN: number
  STAGE_ACTIVITY_INDEX: list
  TRACE_INDEX: list
  BAIYE_ARENA: number
  NEIGONG: number
  CPW: number
  WXZZ: number
  DAZUO: number
  HS_PLAY: number
  ORDER_GU: number
  FOLK_YEZIXI: number
  PVPCS: number
  ROOM_JUDIAN_MATCH: number
  WITNESS: number
  FISHING_CONTEST: number
  EXPEDITION: number
  DUNG_TRUCK: number