Module: hexm.common.consts.reason_consts
Type: table
================================================================================

Keys:
  REASON_QIZHEN_RECYCLE_SUBMIT: string
  REASON_XS_PUBLISH_GET_DEPOSIT: string
  REASON_XS_PUBLISH_PUBLISH: string
  REASON_XS_FINISH_REWARD_TABLE: string
  REASON_INTERACT_DESTRUCT: string
  REASON_NPC_STUFF_KILL: string
  REASON_ACTIVE_INTERACT_RES: string
  _reload_all: boolean
  REASON_XS_PUBLISH_REVERT: string
  REASON_XS_FINISH_REWARD_EXTRA: string
  REASON_NPC_STUFF_ASK: string
  REASON_WYQTP_RECYCLE_SUBMIT: string
  REASON_GACHA_PULL_ACTIVITY: string
  REASON_GACHA_PULL_ACTIVITY_COLLECT: string
  REASON_XS_FETCH_DEPOSIT_REVERT: string
  REASON_INTERACT_RELATION_CHANGE: string
  REASON_NPC_STUFF_SNATCH: string
  REASON_NPC_BEHAVIOR_RECV_STUFF: string
  REASON_ACTIVE_INTERACT_OPEN_DOOR: string
  REASON_NPC_STUFF_STEAL: string
  REASON_DISEASE_REMOVE: string
  REASON_NPC_STUFF_TALK: string
  REASON_YINGXIAO_REWARD: string
  REASON_NPC_STUFF_CHESS: string