Module: hexm.common.consts.region_collect_consts
Type: table
================================================================================

Keys:
  ZHONGSHENG_WSZ: number
  get_max_first_region_progress: function
  COLLECT_TYPE_2_CONFIG_KEY: dict
  EXPLORE_TYPE_2_SUB_TYPE: dict
  EXPLORE_TYPE_CHESS: number
  EXPLORE_TYPE_HUASHU_ST: number
  get_belong_second_region: function
  EXPLORE_REWARD_STATE_CAN_GET: number
  EXPLORE_TYPE_QIYU: number
  get_task_finish_num: function
  COLLECT_TYPE_MULTI_GUARD_WANFA_TYPE: number
  get_region_collect_progress: function
  EXPLORE_TYPE_QUJINGXUNYOU: number
  get_region_jh_progress_by_second_region_id: function
  EXPLORE_TYPE_JMDK: number
  JIANWEN_STATE_CAN_GET: number
  get_common_collect_finish_num: function
  EXPLORE_TYPE_CURIO: number
  COLLECT_TYPE_JUDIAN: number
  get_world_boss_finish_num: function
  _reload_all: boolean
  EXPLORE_TYPE_JUDIAN_FIRST: number
  second_region_check_zhenshou: function
  EXPLORE_REWARD_STATE_NOT_REACH: number
  COLLECT_TYPE_WORLD_BOSS: number
  EXPLORE_TYPE_JUDIAN: number
  EXPLORE_TYPE_TREASURE_GUARD: number
  INTERACT_SRC_TYPE_INS_ENTITY: number
  get_region3_full_explore_score: function
  EXPLORE_TYPE_WITH_SUB_TYPES: list
  EXPLORE_TYPE_AI_NPC: number
  JIANWEN_STATE_RECEIVED: number
  EXPLORE_TYPE2CHECK_FUNC: dict
  EXPLORE_TYPE_JIANWEN: number
  get_unlocked_common_collect: function
  JIANWEN_STATE_LOCKED: number
  EXPLORE_TYPE_YEZIXI: number
  EXPLORE_TYPE_SHICIBAOXIANG: number
  EXPLORE_TYPE_MAJIANG: number
  EXPLORE_TYPE_TOUCH_CAT: number
  COLLECT_TYPE_2_BELONG_SECOND_REGION_CHECK_FUNC: dict
  EXPLORE_TYPE_TREASURE: number
  EXPLORE_TYPE_WULINLU_FIRST: number
  get_region_jh_ever_know_progress: function
  is_ever_know_finish: function
  EXPORT_EXPLORE_TYPE_TREASURE_GUARD: number
  wulinlu_wanfa_is_unlock: function
  EXPLORE_TYPE_WORLD_BOSS: number
  EXPLORE_REWARD_STATE_RECEIVED: number
  COLLECT_TYPE_MULTI_GUARD: number
  (1 more keys)