Module: hexm.common.consts.school_consts
Type: table
================================================================================

Keys:
  SCHOOL_INVITATION_ZFY_3: string
  SCHOOL_GUYUN: number
  REP_3: number
  ORDER_NM_WXZZ: number
  WANFA_TANGZHU: number
  SCHOOL_EVENT_TYPE_AVATAR: number
  SCHOOL_TITLE_DEACON_FOREIGN: number
  REP_8: number
  SCHOOL_EVENT_STATUS: number
  CHASE_FINISH_FLAG_FLEE: string
  SCHOOL_WENJINGUAN: number
  SCHOOL_EVENT_JOIN: number
  ANNOUNCEMENT_MODE_SELF: number
  SCHOOL_JIANGHU: number
  SCHOOL_EVENT_TYPE_JL: number
  SCH_TOT_REP_MAX: number
  RULE_SCBL: string
  SCH_STATE_SPACE_READY_PVP: number
  SCHOOL_INVITATION_JLM_MAP: dict
  CHIEF_SGT_DEFAULT: number
  BLOOD_TYPE_NPC: number
  SCHOOL_JIANGXIANG: number
  SCHOOL_STATUS_CHIEF: number
  SCHOOL_CHARM_MARRY: number
  REP_10: number
  LEARN_STATE_IDLE: string
  STUFF_PARAM_3: string
  SCHOOL_RANK_PREFIX_WEI_REP: string
  school_ceremony_can_invite_tourist: function(state_no)  -- hexm/common/consts/school_consts.lua:212-217
  SCHOOL_EVENT_TYPE_WX: number
  SCHOOL_STATUS_ELDER: number
  SCHOOL_TITLE_MASTER_FOREIGN: number
  CEREMONY_STATE_OVER: string
  SCHOOL_EVENT_QUIT: number
  CEREMONY_STATE_TAKE: string
  get_jl_level: function(school_no, jl_value)  -- hexm/common/consts/school_consts.lua:9-21
  SCHOOL_STATUS_INNER: number
  SCHOOL_WJG_STATUS_LIST: list
  SCHOOL_EVENT_TYPE_SANITY: number
  FILED_STATUS: string
  TITLE_DISMISS_SGT_OVERTIME: string
  RULE_FZYS: string
  SCHOOL_TITLE_DEACON_LEGAL: number
  RPC_CHASE_INFO_BACK: string
  WANFA_ZONGMEN: number
  school_event_type_decode: function(et)  -- hexm/common/consts/school_consts.lua:238-240
  CEREMONY_STATE_TRAP: list
  SCHOOL_TITLE_PUPIL_INTERNAL: number
  SCHOOL_KUANGLAN: number
  CHASE_BILLBOARD_CHASED: string
  ORDER_NM_WFBR: number
  SCHOOL_INVITATION_ZFY_2: string
  SCHOOL_EVENT_LIMIT: number
  SCHOOL_EVENT_RULE: number
  SCHOOL_RULE_JIANZHONG: number
  TOUSHI_GAME_SCUUESS: number
  TOUSHI_GAME_FAIL_LOGIN: number
  CHASE_BILLBOARD_CHALLENGE: string
  LEARN_STATE_QUIZ: string
  get_jl_limit_section: function(school_no, level)  -- hexm/common/consts/school_consts.lua:23-33
  SCHOOL_STATUS_NEED_RANK_SINGLE: list
  TOUSHI_GAME_FAIL_MODE: number
  LEARN_STATE_DESTROY: string
  SCHOOL_INVITATION_JLM_4: string
  SCH_STATE_WAIT_MAP_CAL: number
  school_qingxi_get_own_drug: function(avatar, stuff_id)  -- hexm/common/consts/school_consts.lua:477-485
  SCHOOL_CJ_JL: number
  SCHOOL_QINGXI_DRUG_TAG: string
  E_VOTE_RESULT: string
  SCHOOL_JL_JOIN: number
  ORDER_COND_GU_KILL: number
  CEREMONY_STATE_START: string
  LEARN_STATE_NOPE: string
  REP_5: number
  NOT_JION_SCHOOL: number
  CHIEF_SGT_CHALLENGE: number
  TOUSHI_GAME_FAIL_GIVE_UP: number
  get_demote_status: function(status)  -- hexm/common/consts/school_consts.lua:415-421
  SCHOOL_EVENT_TYPE_COLLECT: number
  ANNOUNCEMENT_MODE_NONE: number
  TOUSHI_GAME_FAIL_PRIORITY: number
  CEREMONY_STATE_VOW: string
  ORDER_COND_EVENT: dict
  UNLOCK_SCHOOL_RULE_ORDER: string
  TITLE_APPOINT_SGT_CHALLENGE: string
  ORDER_NM_GU: number
  RULE_TYPE_WEEK: number
  get_qingxi_stuff_tab: function(stuff_no)  -- hexm/common/consts/school_consts.lua:487-512
  SCH_STATE_QUA_YES: number
  LEARN_OVER_BOSS_DEAD: number
  TITLE_DISMISS_SGT_CHALLENGE: string
  CHASE_FINISH_FLAG_GIVE_UP: string
  LEARN_OVER_QUIT: number
  SCH_STATE_SPACE_INIT: number
  SCHOOL_TITLE_LEADER: number
  CHASE_FINISH_FLAG_DEFAULT: string
  SCHOOL_APPRENTICE_TYPE: list
  SCHOOL_JL_ADD: number
  TOUSHI_GAME_FAIL_TIMEOUT: number
  LOGIN_MENPAI_ENTER_TIP: dict
  SCHOOL_FREEDOM: number
  SCHOOL_EVENT_TYPE_TITLE: number
  SCHOOL_LIYUAN: number
  SCH_REP_MAX: number
  school_event_type: function(event_type, score)  -- hexm/common/consts/school_consts.lua:234-236
  school_qingxi_get_drug_status: function(avatar, stuff_id)  -- hexm/common/consts/school_consts.lua:467-475
  SCHOOL_JL_PUNISH: number
  CEREMONY_STATE_READY: string
  TOUSHI_GAME_FAIL_LEAVE_SPACE: number
  LEARN_STATE_FIGHT: string
  SCHOOL_TITLE_NONE: number
  SCHOOL_STUB_PREFIX: string
  RULE_KILL: string
  SCHOOL_CHARM_LIKE: number
  CEREMONY_STATE_DELIVERY: string
  REP_6: number
  FILED_EVENT: string
  SCHOOL_INVITATION_JLM_1: string
  CEREMONY_STATE_WAIT: string
  PLAY_CEREMONY: number
  TYPE_NONE_CHOICE: number
  SCHOOL_TITLE_PUPIL_LEGAL: number
  ORDER_NM_SNZD: number
  SCHOOL_RANK_PREFIX_WEI: string
  ORDER_COND_KEY: dict
  LEARN_OVER_GUARANTEED_TIMER: number
  ORDER_NM_DRINK: number
  SCHOOL_TITLE_DEACON_INTERNAL: number
  LEARN_STATE_QTE: string
  MAIL_SUC: number
  school_status_identity: function(status_str)  -- hexm/common/consts/school_consts.lua:423-428
  TYPE_NONE_SCHOOL: number
  RULE_NM_JLM: number
  CEREMONY_STATE_MASTER: string
  RULE_NM_TDYZ: number
  SCH_TOT_REP_MIN: number
  TOUSHI_GAME_FAIL_NORMAL_LIST: list
  ORDER_NM_WJJL: number
  SCH_STATE_BATTLE: number
  SCHOOL_TITLE_PUPIL_FOREIGN: number
  SCHOOL_LEARN_STEAL: number
  SCHOOL_INVITATION_TQ_1: string
  SCH_WAIT_STATES: list
  SCHOOL_CJ_BETRAY: number
  FILED_DATA: string
  SCHOOL_TITLE_MASTER_INTERNAL: number
  SCHOOL_QINGXI: number
  MAIL_OTHER: number
  SCH_STATE_ENROLL: number
  CEREMONY_STATE_DESTROY: string
  ANNOUNCEMENT_MODE_ALL: number
  ORDER_NM_HELL: number
  SCHOOL_EVENT_TYPE_RULE: number
  RULE_DRUNK: string
  SCHOOL_CHARM_GIFT: number
  E_START_VOTE: string
  BLOOD_TYPE_ANIMAL: number
  SCHOOL_INVITATION_ZFY_4: string
  SCHOOL_RANK_PREFIX_REP: string
  TOUSHI_GAME_FAIL_LOSE_CLIENT: number
  MAIL_FAIL: number
  SCHOOL_STATUS_DIRECT: number
  SCHOOL_JL_TIMEOUT: number
  SCHOOL_LEARN_OUTER: number
  _reload_all: boolean
  SCHOOL_TITLE_MASTER_LEGAL: number
  get_promote_status: function(status)  -- hexm/common/consts/school_consts.lua:404-409
  REP_4: number
  FILED_EVENT_REPORT: string
  PLAY_SEL_ZFT: number
  TOUSHI_GAME_FAIL_ERROR_LIST: list
  RULE_KILLED: string
  REP_1: number
  RULE_GUILTY: string
  SCHOOL_ZUIHUAYIN: number
  RULE_NM_JJTX: number
  SCHOOL_INVITATION_JLM_2: string
  RULE_TDYZ: string
  SCHOOL_QINGXI_DRUG_STATUS_NO_DISTINGUISH: number
  PIC_BODY_TYPE: string
  SCH_STATE_IDLE: number
  CEREMONY_STATE_IDLE: string
  RULE_NM_JZZZ: number
  ORDER_NM_MONK: number
  TOUSHI_GAME_FAIL_LEAVE_REGION: number
  LEARN_STATE_BEGIN_ANIM: string
  RULE_SGWH: string
  BLOOD_TYPE_PLAYER: number
  RULE_QBZS: string
  LEARN_STATE_OVER: string
  REP_9: number
  SCHOOL_QINGXI_DRUG_STATUS_DISTINGUISHED: number
  SCHOOL_CHARM_NEITUI: number
  SCHOOL_SANGENGTIAN: number
  ORDER_NM_CHASE: number
  tq_reason_map: dict
  ORDER_NM_JRFQ: number
  STUFF_PARAM_4: string
  RULE_NM_SXTW: number
  REP_2: number
  CEREMONY_STATE_EVENT: dict
  SCHOOL_DB_COL: string
  SCH_TEST_OVER_STATES: list
  TYPE_SCHOOL: number
  ORDER_NM_YINGFU: number
  SCHOOL_EVENT_REPORT_LIMIT: number
  SCHOOL_STATUS_OUTER: number
  ORDER_COND_GU_SURVIVAL: number
  SCH_STATE_WAIT: number
  get_promote_percent: function(school_status)  -- hexm/common/consts/school_consts.lua:400-402
  SCH_ENROLL_STATES: list
  SCHOOL_INVITATION_JLM_3: string
  STUFF_PARAM_1: string
  SCHOOL_TIANQUAN: number
  REP_7: number
  SCH_STATE_WAIT_OTHER_PLAYER: number
  LEARN_OVER_AVATAR_DEAD: number
  CHASE_BILLBOARD_CHASER: string
  PLAY_APPRENTICE: number
  ORDER_NM_RYSX: number
  LEARN_STATE_LEAK: string
  NAME_JZ: string
  STUFF_PARAM_LIST: list
  BODY_TYPE_DESC: dict
  RULE_TYPE_AT_ONCE: number
  SCHOOL_LEARN_INNER: number
  SCHOOL_JL_DEDUCT: number
  SCHOOL_INTRO_LIMIT: number
  JL_BILLBOARD: string
  SCHOOL_CHARM_CHEGAO: number
  RULE_JZ: string
  CEREMONY_STATE_TAKE_ANIM: string
  SCHOOL_CJ_ALL: number
  SCH_STATE_QUA_NO: number
  SCHOOL_INVITATION_ZFY_1: string
  RULE_TYPE_NOPE: number
  ORDER_COND_GU_DAMAGE: number
  SCH_STATE_SPACE_GAME_OVER: number
  get_demote_percent: function(school_status)  -- hexm/common/consts/school_consts.lua:411-413
  STUFF_PARAM_2: string
  SCH_REP_MIN: number
  SCHOOL_RULE_TYPE: list
  ORDER_COND_GU_STUFF: number
  LEARN_CAMP_ENEMY: number
  SCHOOL_JL_QUIT: number
  SCHOOL_EVENT_TYPE_SCHOOL: number
  RULE_RED: string
  CHASE_BILLBOARD_PIC: string
  LEARN_CAMP_FRIEND: number
  TOUSHI_GAME_FAIL_NORMAL: number