Module: hexm.common.consts.space_room_consts
Type: table
================================================================================

Keys:
  ROOM_WANFA_INVITE_REPLY: number
  DISCARD_ROOM: number
  TRANFER_ID_WANFA_LOADING: number
  TRANFER_ID_COOP_TO_SINGLE: number
  ROOM_CUST_TAG_ADD: number
  get_default_apply_msg: function()  -- hexm/common/consts/space_room_consts.lua:267-269
  NOT_TEAM_LEADER: number
  OWNER_BE_CALL: number
  ROOM_WANFA_OVER: number
  HAS_WANFA_STATE: number
  GET_WANFA_AUTH: number
  TEAM_JUDIAN_ONE: number
  ADD_WANFA_AUTH_BY_HOSTER: number
  get_main_player_invite_msg: function()  -- hexm/common/consts/space_room_consts.lua:262-265
  ERR_REMIND_START: number
  YEZIXI: number
  ENTER_STATE_DISABLE: number
  DEAL_BE_INVITE: number
  INVITE_ALL_PLAYER: number
  E_ROOM_WANFA_START_SUGGEST: number
  ROOM_WANFA_LEAVE: number
  TRASFER_ID_COOP: number
  NOT_SELF_SPACE: number
  DENY_APPLY: number
  INVITE_IN_CD: number
  LUNJIAN2V2: number
  QUIT_TEAM: number
  NOT_ROOM_OWNER: number
  EDIT_DEAD: number
  room_check_show_result: function(time, online_point)  -- hexm/common/consts/space_room_consts.lua:325-332
  ROOM_WANFA_DES: number
  INTER_TIME: number
  DOUDIZHU: number
  LEAVE_MY_ROOM: number
  NOT_IN_SELF_SPACE: number
  COOP_ROOM: number
  TIANXIA_HUWUI: number
  NEIGONG: number
  HUPAI: number
  ROOM_CUST_TAG_RM: number
  TEAM_JUDIAN_FIVE: number
  KICK_PLAYER: number
  TEAM_JUDIAN_FOUR: number
  SHOW_STATE: table <UnknownInstance>
  ENTER_STATE_ENABLE: number
  AFFINITY_OWNER: number
  ADD_WANFA_AUTH: number
  BE_CALL_TOGETHER: number
  FTW: number
  OTHER_NOT_IN_SELF_SPACE: number
  EDIT_WF: number
  TEAM_JUDIAN_JZHS: number
  MWZX: number
  NOT_CREATE_ROOM: number
  NOT_COOP_MODE: number
  SHEFU: number
  check_world_level_gap: function(level)  -- hexm/common/consts/space_room_consts.lua:309-320
  ROOM_HELP_HINT: number
  ALREADY_HAS_ROOM: number
  LONG_TEXT_LIMIT: number
  AFFINITY_EXTRA: number
  MULTI_THERAPY: number
  ROOM_CUST_TAG_CLEAR: number
  LONGMEN_INN_NIGHT: number
  ERR_OWNER_REJECT_START: number
  BE_APPLY_ENTER: number
  LUNJIAN3V3: number
  SUMO: number
  ROOM_WANFA_INVITE: number
  INVITE_TIME_LIMIT: number
  LUNJIAN1V1: number
  PB_BUILD: number
  HOMEWORLD_SPACENO: number
  E_UDS_ROOM_DELAY_INVITE: number
  SPECIAL_TRAINING: number
  GET_WANFA_AUTH_BY_HOSTER: number
  INFORM_RESULT_INVITE: number
  ROOM_WANFA_BE_INVITED: number
  CREATE_ROOM: number
  ROOM_CANNOT_BE_APPLY: number
  ROOM_WANFA_JOIN: number
  OTHER_ALREADY_HAS_ROOM: number
  CALL_TOGETHER: number
  CANNOT_BE_INVITE: number
  TEAM_JUDIAN_TWO: number
  OTHER_ENTER: number
  CANCEL_WANFA_AUTH: number
  _reload_all: boolean
  OTHER_IS_OFFLINE: number
  SZYY: number
  ROOM_WANFA_CREATE: number
  DOUDIZHU_COMP_SINGLE: number
  CANCEL_WANFA_AUTH_BY_HOSTER: number
  ROOM_WANFA_DES_BE_TELL: number
  OTHER_LEAVE: number
  CHIJI_SINGLE: number
  TIP_ROOM_WANFA_START: number
  ROOM_WANFA_LEAVE_BE_TELL: number
  SENSITIVE_ERROR: number
  TEAM_JUDIAN_THREE: number
  LEAVE_OTHER_ROOM: number
  PB_RS: number
  ROOM_WANFA_FULL_ENTER: number
  BE_INVITED: number
  INVITE_PLAYER: number
  MSG_TEXT_LIMIT: number
  TIP_NOTIFY_OWNER_LEAVE: number
  NOT_UNLOCK_ROOM: number
  ENTER_MY_ROOM: number
  APPLY_ENTER: number
  REASON_WANFA_KICK_LEAVE: string
  ROOM_GET_TARGET: number
  AUTHORITY: string
  EDIT_CUST: number
  MAJIANG: number
  CLUB_MULTI_BATH: number
  get_main_player_apply_msg: function()  -- hexm/common/consts/space_room_consts.lua:257-260
  ROOM_WANFA_START: number
  BE_INVITE_ALL_PLAYER: number
  CANNOT_INVITE_SELF_ROOM: number
  AFFINITY_APPLIER: number
  ERR_APPLYED_TO_OWNER: number
  get_invite_msg_by_data: function(data)  -- hexm/common/consts/space_room_consts.lua:275-291
  UPDATE_SELF_SET: number
  OTHER_IN_HUGE_TEAM: number
  NO_INVITE_RIGHT: number
  ANTIQUE_COLLECT_QH: number
  DEFAULT_APPLY_MSG: number
  CHIJI_TEAM: number
  FIREWORK: number
  BE_OUT_ROOM: number
  ROOM_WANFA_POP_MEMBER: number
  TEAM_CREATE_ROOM_NUM_LIMIT: number
  INFORM_RESULT_APPLY: number
  EDIT_NEARBY: number
  INVITE_NO_ONE: number
  TIP_CONFIRM_OWNER_LEAVE: number
  ERR_TASK_REGION_OWNER: number
  OTHER_NOT_UNLOCK_ROOM: number
  ROOM_WANFA_SET_PLAYER_NUM: number
  ENTER_OTHER_ROOM: number
  ROOM_IS_CLOSE: number
  GET_ROOM_MEMBERS: number
  DEFAULT_INVITE_MSG: number
  get_wanfa_name_by_invite_data: function(invite_data)  -- hexm/common/consts/space_room_consts.lua:293-307
  GYMNASTICS: number
  ROOM_WANFA_FULL_APPLY: number
  MUL_RHYTHM_FOLLOW: number
  get_default_invite_msg: function()  -- hexm/common/consts/space_room_consts.lua:271-273
  PITCH_POT: number
  ROOM_TAG_SET: number
  QUIT_ROOM: number
  REASON_WANFA_LEAVE: string
  UPDATE_ROOM_SET: number
  DANCE: number
  DES_MY_TEAM: number
  E_UDS_ROOM_APPLY_ENTER: number
  BE_KICK: number
  MOJIN_SHAREN: number
  PHOTO_POINT: number
  CHIJI_DUO: number
  LEAVE_ROOM: number
  MOJIN_XUNBAO: number
  GET_ROOM_DATA: number
  room_check_can_online: function(avatar, is_self, skip_dict)  -- hexm/common/consts/space_room_consts.lua:334-388
  CHECK_PLAYER_CAN_ENTER_ROOM: number
  TASK_RANGE: dict
  TEAM_FULL: number
  ANSWER: number
  HAS_OTHER_TEAM: number
  INVITE_CD: number
  RETURN_TOGETHER: number
  LOW_GAME_PRIORITY: number