Module: hexm.common.consts.state_consts
Type: table
================================================================================

Keys:
  NAVIGATE: string
  MODE_COOP_VALID_STATES: list
  FLY: string
  SUNSHINE_TRIGGER_STATES: list
  E_S_SLIDE: string
  CHOSEN_TARGET_NEED_WATCH_STATES: list
  BEHIT: string
  E_S_DEAD: string
  E_S_DEFENCE: string
  DIALOGS: string
  E_S_REVIVE: string
  DYING: string
  RUN: string
  E_S_KEEP_ANIM: string
  E_S_DIANXUE: string
  GAMEPLAY_GAME_LEVEL: string
  CLUE_INVESTIGATE: string
  GAMEPLAY_TAKE_CARRIAGE: string
  E_S_APPROACH: string
  GAMEPLAY: string
  E_S_BEHIT: string
  E_S_INTERACT: string
  DISEASE: string
  E_S_CLIMB_ROCK: string
  GAMEPLAY_WATER_TURRET: string
  E_S_CLUE_INVESTIGATE: string
  GAMEPLAY_RHYTHM_GAME: string
  E_S_NARROW_MOVE: string
  GAMEPLAY_CLUB_ROOM: string
  E_S_RIDE_ANIM: string
  E_S_NEIGONG: string
  E_S_PLATFORM: string
  E_S_GRIP_HAND: string
  GAMEPLAY_JIEYUAN_ANSWER: string
  NEIGONG: string
  FALL: string
  GAMEPLAY_DIE_DIE_LE: string
  WALK: string
  E_S_GAMEPLAY: string
  SWIM: string
  E_S_SLIP: string
  E_S_DRESS_PREVIEW: string
  GAMEPLAY_SUMO: string
  E_S_WAIT_RPC: string
  E_S_NAVIGATE: string
  GAMEPLAY_CLUB_AUTO_BUILD_ACC: string
  GAMEPLAY_DRINK_PITCH_POT: string
  E_S_RUN: string
  LADDER: string
  E_S_CUTSCENE: string
  WAIT_THERAPY: string
  DEAD: string
  GAMEPLAY_STACKING: string
  GAMEPLAY_HOLD_ON_CARRIAGE: string
  E_S_END_NAVIGATE: string
  E_S_IDLE: string
  GAMEPLAY_ANIM_ACTION: string
  GAMEPLAY_RIDE_ANIM_ACTION: string
  E_S_LADDER: string
  E_S_LISTEN: string
  E_S_FALL: string
  GAMEPLAY_TOUCH_CAT: string
  GAMEPLAY_PRISON_PARADE: string
  GAMEPLAY_FLAME_TURRET_BULLET: string
  GAMEPLAY_BAIYE_TRUCK: string
  DIAGNOSE: string
  E_S_FLIP_WINDOW: string
  E_S_SWIM: string
  ST_MAP_CLUE_INVEST: number
  E_S_ACTION_GROUP: string
  GAMEPLAY_CLUB_MASSAGE: string
  WAIT_RPC: string
  E_S_WATCH_FACE: string
  SKILL: string
  EAVESDROP: string
  E_S_RIDE_ANIM_RUN: string
  APPROACH: string
  NO_FALLHURT_STATE: list
  GAMEPLAY_BUILD_QTE: string
  E_S_DYING: string
  E_S_DIAGNOSE: string
  SHADOW_PLAY: string
  E_S_STICK_WALL: string
  SLIP: string
  E_S_SHADOW_PLAY: string
  GAMEPLAY_RONGLU_LADDER: string
  TREAD: string
  REVIVE: string
  DRESS_PREVIEW: string
  GAMEPLAY_WENSHI_MULTI_ANSWER: string
  GAMEPLAY_DOUDIZHU: string
  E_S_READ: string
  GAMEPLAY_SHEFU: string
  E_S_SKILL: string
  GAMEPLAY_DEBATE_BATTLE_SPECTATOR: string
  GAMEPLAY_BAIYE_BATTLE_QTE: string
  GAMEPLAY_SWING: string
  GAMEPLAY_TJZ: string
  CUTSCENE: string
  STICK_WALL: string
  GAMEPLAY_ROTATE_ENTITY: string
  E_S_WAIT_THERAPY: string
  GAMEPLAY_ZAOTANG_MASSAGE: string
  GAMEPLAY_MAHJONG: string
  E_S_EAVESDROP: string
  GAMEPLAY_HAND_GEAR: string
  GAMEPLAY_CRANE: string
  LISTEN: string
  E_S_CONTROL: string
  E_S_CLIMB: string
  WANFA_STORYLINE: string
  SITDOWN: string
  GAMEPLAY_HOSPITAL_THERAPY: string
  SLIDE: string
  E_S_THERAPY: string
  DRIVE: string
  GAMEPLAY_HUPAI: string
  GAMEPLAY_DISEASE: string
  ACTION_GROUP: string
  name_to_event: function(name)  -- hexm/common/consts/state_consts.lua:234-236
  WATCH_FACE: string
  E_S_DRIVE: string
  GAMEPLAY_PLAY_FIREWORKS: string
  E_S_FLY: string
  DEFENCE: string
  LOADING_GATE: string
  GAMEPLAY_DRINK_QTE: string
  READ: string
  E_S_CLIMB_FREE: string
  E_S_LOADING_GATE: string
  DONKEY_RIDING: string
  E_S_SITDOWN: string
  E_S_DONKEY_RIDING: string
  GRIP_HAND: string
  GAMEPLAY_SCOUTING: string
  E_S_WALK: string
  FLIP_WINDOW: string
  GAMEPLAY_DEBATE_BATTLE: string
  GAMEPLAY_SCHOOL_ARREST: string
  GAMEPLAY_CUJU: string
  GAMEPLAY_BATTLE_SPAR: string
  GAMEPLAY_ZAOTANG_LAY: string
  IDLE: string
  GAMEPLAY_ZAOTANG_POOL: string
  GAMEPLAY_INSTRUMENT: string
  E_S_DIALOGS: string
  DIANXUE: string
  GAMEPLAY_PHOTOGRAPH: string
  GAMEPLAY_ZUIHUAYIN_DANCE: string
  GAMEPLAY_BLUFF_POKER: string
  GAMEPLAY_FISHING: string
  GAMEPLAY_TOUSHI_QTE: string
  GAMEPLAY_COLOR_MIX: string
  THERAPY: string
  INTERACT: string
  STATES_RELAY_MAINTAIN: list
  STATES_REPORT_SERVER: list
  PLATFORM: string
  NARROW_MOVE: string
  RIDE_ANIM: string
  GAMEPLAY_GUHUO: string
  event_to_name: function(event)  -- hexm/common/consts/state_consts.lua:227-231
  E_S_TREAD: string
  SERVER_STATES: list
  STATES_REPORT_CLIENT_SPACE: list
  KEEP_ANIM: string
  SERVER_TRIGGER_STATES: list
  GAMEPLAY_FLAME_TURRET: string
  LOCAL_ST_AS_SERVER: dict
  GAMEPLAY_DICE_GAME: string
  E_S_DISEASE: string
  CONTROL: string
  GAMEPLAY_SHRINK_BONE_TURRET: string
  CLIMB_ROCK: string
  GAMEPLAY_SIMPLE_SITDOWN: string
  GAMEPLAY_INFERENCE_CLUE: string
  ST_MAP_BASE: number
  CLIMB: string
  E_S_WANFA_STORYLINE: string
  GAMEPLAY_DUNG_TRUCK: string
  CLIMB_FREE: string
  GAMEPLAY_COOK_QTE: string