Module: hexm.common.consts.tag_consts
Type: table
================================================================================

Keys:
  TYPE_WEAPON: number
  main_type_value: function(type_value)  -- hexm/common/consts/tag_consts.lua:122-130
  TAG_SUB_BUILDING_NORMAL: number
  TYPE_COMMON_PLAY: number
  TYPE_COMPOSITION_ITEM: number
  TAG_SUB_BUILDING_SIMPLE: number
  TAG_ANIMAL_NPC_BIT: number
  TYPE_POINT: number
  SUB_TYPE_BIT: number
  TAG_MAIN_BUILDING: number
  base_tag: function(bit_value)  -- hexm/common/consts/tag_consts.lua:45-47
  TAG_VEHICLE_BIT: number
  TAG_PORRIDGE_SHOP: number
  TAG_BASE_MAIN_PLAYER_BIT: number
  sub_type: function(type_bit)  -- hexm/common/consts/tag_consts.lua:231-233
  TAG_COLLECT_MINE: number
  TAG_COLLECT_TREE: number
  TYPE_DESTRUCT: number
  SUBTYPE_IDLER_NPC: number
  TYPE_MONSTER: number
  TAG_BUILDING_BIT: number
  TAG_BASE_SPACE_DATA_BIT: number
  TAG_BASE_NPC_BIT: number
  TAG_MAIN_PORRIDGE_SHOP: number
  SUBTYPE_BOSS: number
  SUBTYPE_NORMAL_BUILDING: number
  TAG_PLANT_TRUNK: number
  TAG_NORMAL_INTERACTCOM: number
  TAG_BUILDING_COMPOSITION: number
  SUBTYPE_ROBOT_NPC: number
  TAG_BASE_PLANT_TRUNK_BIT: number
  TAG_COLLECT_GRASS: number
  TAG_SUB_ELITE_MONSTER_BIT: number
  TYPE_NORMAL_LOCAL_ENTITY: number
  TAG_MAIN_NORMAL_LOCAL_ENTITY_BIT: number
  SUBTYPE_PET_DOG_NPC: number
  TAG_MAIN_COLLECT_BIT: number
  SUBTYPE_ANIMAL_NPC: number
  TAG_LOCAL_ENTITY: number
  TYPE_NPC_INTERACT: number
  TAG_MAIN_WEAPON_BIT: number
  new_tags: table <UnknownInstance>
  TAG_SUB_BUILDING_BLUEPRINT: number
  TAG_MAIN_NPC_BIT: number
  TYPE_AIAVT: number
  SUBTYPE_LAND: number
  TAG_MAIN_MONSTER_BIT: number
  TAG_BASE_TRAP_BIT: number
  TAG_MAIN_COMPOSITION_ITEM: number
  SUBTYPE_CONSUME_NPC: number
  TAG_COMMON_PLAY: number
  TAG_SUB_GROUP_BUILDING: number
  TAG_MAIN_PLAYER: number
  TAG_BASE_MAGIC_FIELD_BIT: number
  TAG_TREASURE_BOX: number
  TYPE_SPACE_INTERACT: number
  SUBTYPE_COLLECT_TREE: number
  TAG_BASE_LOCAL_ENTITY_BIT: number
  TAG_MAIN_AIRWALL_BIT: number
  TYPE_RIDE: number
  SUBTYPE_GROUP_BUILDING: number
  TAG_OTHER_PLAYER: number
  TAG_IDLER_NPC_BIT: number
  TYPE_NPC_COLLECT: number
  TAG_MAIN_RIDE_BIT: number
  TAG_SHOP: number
  TYPE_AIRWALL: number
  TYPE_NPC: number
  TAG_TASK_NPC_BIT: number
  TAG_MAIN_INTERACT_BIT: number
  SUBTYPE_SIMPLE_BUILDING: number
  SUBTYPE_TASK_NPC: number
  TAG_RADIATION_BIT: number
  TAG_FOLIAGE_BIT: number
  TAG_VEHICLE: number
  TAG_INTERACT_COMPONENT: number
  SUBTYPE_TREASURE_BOX: number
  USE_NEW_TAG_SYSTEM: boolean
  is_client_interactcom_by_sid: function(spaceno, sid)  -- hexm/common/consts/tag_consts.lua:373-385
  TAG_AI_AVATAR: number
  TAG_RADIATION: number
  TAG_BUILDING: number
  TAG_MAIN_BASE_POINT_BIT: number
  TAG_NONE: number
  TAG_LAND: number
  TAG_SHOP_BIT: number
  BASE_TYPE_BIT: number
  main_type: function(type_bit)  -- hexm/common/consts/tag_consts.lua:116-118
  TAG_TRAP: number
  TAG_SUB_ROBOT_NPC_BIT: number
  MAIN_TYPE_BIT: number
  TAG_MAIN_SPACE_INTERACT: number
  TYPE_FOLIAGE: number
  TAG_SUB_SMALL_BOSS_BIT: number
  TYPE_BUILDING: number
  TAG_PET_DOG_NPC_BIT: number
  TAG_MAIN_DESTRUCT_BIT: number
  TAG_BASE_OTHER_PLAYER_BIT: number
  TAG_SUB_BOSS_BIT: number
  TAG_SPACE_DATA: number
  TYPE_PORRIDGE_SHOP: number
  TAG_SUB_NORMAL_MONSTER_BIT: number
  TAG_NPC: number
  TAG_INTERACT_COMPONENT_BIT: number
  TAG_CONSUME_NPC_BIT: number
  is_server_interactcom_by_sid: function(spaceno, sid)  -- hexm/common/consts/tag_consts.lua:359-371
  TAG_MAIN_AIAVT_BIT: number
  SUBTYPE_ELITE_MONSTER: number
  SUBTYPE_COLLECT_MINE: number
  SUBTYPE_BUILDING_BLUEPRINT: number
  TAG_AI_AVATAR_BIT: number
  SUBTYPE_COLLECT_GRASS: number
  SUBTYPE_NORMAL_MONSTER: number
  MAINTYPE_NORMAL_INTERACTCOM: number
  SUBTYPE_SMALL_BOSS: number
  TAG_BUILDING_HOUSE: number
  TAG_MAGIC_FILED: number