Module: hexm.common.consts.yezixi_consts
Type: table
================================================================================

Keys:
  CARD_NO_5: number
  SYNC_ACTION: number
  ACTION_FAIL_INVALID_ACTION_DATA: number
  ACTION_SUCCESS: number
  STATE_END: number
  STATE_GAME: number
  timeout_play_card_num: function
  ACTION_UNION_DOUBT: number
  STATE_PLAYER_GAME: number
  SUB_REASON_POSION_MAP: dict
  CARD_NO_6: number
  STATE_PLAYER_LEAVE: number
  ACTION_FAIL_INVALID_ACTION: number
  ACTION_FAIL_NOT_IN_GAME: number
  get_drunk_poison_rate: function
  END_GAME_SUB_REASON_EMPTY_CARDS: number
  END_GAME_SUB_REASON_DRUNK_POISON_DOUBT: number
  CARD_NO_7: number
  get_yezixi_entity: function
  AI_CARD_JOKER: number
  CARD_TYPE_2: number
  _extra_punish_drunk: function
  _reload_all: boolean
  CARD_NO_10: number
  CARD_NO_4: number
  STATE_PLAYER_POISON: number
  CARD_TYPE_3: number
  ACTION_UNION_FIRST: number
  GAME_KEY_COOP: string
  DEFAULT_DRUNK_UNIT: number
  CARD_NO_3: number
  _calc_drunk_balance: function
  CARD_NO_1: number
  SYNC_TURN_STATR: number
  END_GAME_SUB_REASON_DRUNK_POISON_RENFA: number
  CARD_NO_8: number
  _calc_drunk_unit: function
  FIRST_ROUND_CARD: number
  CARD_TYPE_4: number
  timeout_play_card_no: function
  ACTION_DOUBT: number
  ACTION_GIVE_UP: number
  CARD_TYPE: dict
  END_GAME_REASON_DRUNK: number
  ACTION_UNION_FOLLOW: number
  get_card_no: function
  is_ty_game: function
  END_IMMEDIATELY_SUB_REASON: list
  GAME_KEY_DUNGEON: string
  END_GAME_REASON_LEAVE: number
  (1 more keys)