Module: hexm.client.debug.gm.gm_commands.gm_build
Type: table
================================================================================

Keys:
  interactcom_use_hex_model: function
  build_put_on: function
  gm_build_restore_preset: function
  check_building_sys_d_and_recipe_sys_d: function
  put_prefab_as_blueprint_in_main_space: function
  debug_show_engine_static_entity_axis: function
  test_building: function
  free_building_enable_main_world_num_limit_8000: function
  building_prefab_enable_merged_model: function
  print_adsorb_rules: function
  _reload_all: boolean
  gm_add_bp_prefab_comps_on_one_bp: function
  show_bp_comp_nums: function
  debug_show_pt_area: function
  building_pt_use_hex_model: function
  gm_free_building_transfer_prefab_list_to_blueprint: function
  interactcom_use_simple_entity: function
  debug_show_bp_set_pos_points: function
  gm_check_variant_comp: function
  gm_add_all_building_items: function
  delete_build_db: function
  gm_free_building_transfer_single_build_to_blueprint: function
  show_bp_entity_comp_nums: function
  put_prefab_in_bp_space: function
  free_building_enable_lb: function
  all_compositions: list
  building_blueprint_enable_save_blueprint_in_main_world: function
  debug_show_client_static_entity_axis: function
  blueprint_set_state_shadow_ban: function
  show_industry_building_size: function
  building_use_hex_phyx: function
  gm_free_build_clear: function
  print_bp_data_status: function
  interactcom_use_hex_anim: function
  export_blueprint_file: function
  gm_free_building_export_bp: function
  free_building_hex_model_fill_empty_lod: function
  gm_check_comp_show: function
  gm_bp_design_correct_pos_with_atmosphere: function
  debug_show_ladder_connections: function
  skip_space_check: function
  debug_show_enter_ladder: function
  gm_free_building_save_all: function
  bp_design_set_comp_is_not_foundation: function
  debug_print_building_connected_graph: function
  gm_check_comp_compound: function
  show_build_no_bp_status: function
  free_building_enable_lb_debug_draw: function
  dis_blueprint_comp_by_no: function
  debug_show_building_grid_area: function
  (1 more keys)