Module: hexm.client.debug.gm.gm_commands.gm_camera
Type: table
================================================================================

Keys:
  set_combat_camera_target_bone_name: function
  free_camera: function
  show_camera_target_pos: function
  try_leave_watch_face: function
  gm_set_base_camera_clear: function
  camera_generate_icon: function
  show_camera_mode_stack_window: function
  gm_set_base_camera_curr_distance: function
  _on_camera_proximity_transform_changed: function
  show_camera_mode_stack: function
  camera_blender_leave: function
  camera_blender_no: function
  camera_apply_template: function
  set_combat_camera_data_B: function
  hide_all_world: function
  _reload_all: boolean
  try_pivot_mode: function
  gm_set_base_camera_new_target: function
  try_enter_watch_face: function
  set_combat_camera_data_A: function
  try_close_length_checker: function
  clear_combat_camera_data: function
  _free_camera: boolean
  high_resolution_snapshot: function
  camera_blender_set: function
  gm_set_base_camera_distance_info: function
  test_camera_shake: function
  is_free_camera: function
  test_camera_fov: function
  camera_save_template: function
  _is_open_player_charctrl: boolean
  free_camera_speed: function
  set_main_player_charctrl: function
  save_combat_camera_data: function
  is_open_player_charctrl: function