Module: hexm.client.debug.gm.gm_commands.gm_combat
Type: table
================================================================================

Keys:
  gm_open_combat_train: function
  gm_entities_mortal: function
  _bot_rand_skill: function
  echo_property: function
  gm_lock_target: function
  show_gm_set_main_kongfu: function
  niubility: function
  gm_show_npc_collision_box: function
  trigger_bot: function
  gm_recover: function
  gm_show_damage_panel: function
  gm_debug_show_calc_bone: function
  add_buff: function
  generate_faction_list: function
  add_attr: function
  _reload_all: boolean
  gm_save_damage_panel: function
  gm_unlock_target: function
  gm_connect_to_messiah_monitor: function
  equip_weapon: function
  gm_enable_stopframe_debug: function
  gm_forbid_behit_highlight: function
  gm_kill_npcs: function
  show_boss_enter_leave_battle_region: function
  gm_avatar_mortal: function
  gm_unlimited_dive_resource: function
  generate_weapon_params: function
  test_remove_resource_mode: function
  gm_skill_slot_test: function
  show_skill_target_weight: function
  generate_pvp_lock_target_list: function
  gm_set_invincible: function
  gm_become_powerful1: function
  gm_empty_combat_resource: function
  test_add_resource_mode: function
  gm_play_fight_to_idle: function
  show_combat_region: function
  gm_limit_mouse_func: function
  gm_show_invincible_trigger: function
  gm_debug_attack_stopframe: function
  gm_show_damage_panel_entity: function
  change_weapon: function
  gm_debug_behit_stopframe: function
  gm_lock_res_consume: function
  gm_kongfu_upgrade: function
  gm_play_idle_to_fight: function
  gm_exec_gm_boss_test: function
  gm_reset_combat_resource: function
  gm_remove_buff: function
  gm_enable_player_collision: function
  (1 more keys)