Module: hexm.client.debug.gm.gm_commands.gm_guide
Type: table
================================================================================

Keys:
  close_guide: function
  gm_clear_guide_tujian: function
  gm_finish_curr_guide: function
  gm_finish_dungeon: function
  gm_unlock_guide_tujian: function
  gm_finish_guide: function
  open_npc_limit: function
  clear_bg_finished: function
  clear_guide: function
  gm_unlock_all_guide_tujian: function
  switch_guider_detect: function
  gm_unlock_sprite_wiki_id: function
  gm_guide_periods_by_window_name: function
  gm_quick_3v3: function
  switch_guider_state: function
  switch_yugao_state: function
  gm_guide_period: function
  gm_create_player_imp: function
  gm_change_school_imp: function
  gm_test_storyline: function
  gm_finish_current_guide: function
  gm_search_wiki_title: function
  gm_unlock_sprite_wiki: function
  gm_test_storyline_pro: function
  gm_finish_guide_precondition: function
  gm_enable_guide: function
  gm_guide_test_guide: function
  gm_finish_common_condition: function
  gm_unlock_all_sprite_wiki: function
  gm_clear_guide: function
  close_npc_limit: function
  finish_battle_guide: function
  gm_finish_all_guides: function
  gm_finish_xsshou_dungeon: function
  gm_open_guide_debug_panel: function