Module: hexm.client.debug.gm.gm_commands.gm_normal
Type: table
================================================================================

Keys:
  charge_sid_yysls.6battlepass01: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_cdkey: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_skill_pg: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  draw_aiavt_move_range_cylinder: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  goto_button: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_print_cutscene_pos: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  ai_lab_account_back: function(err_no, data)  -- hexm/client/debug/gm/gm_commands/gm_normal.lua:3013-3021
  gm_unlock_one_title: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_transfer_ignore_region2: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_tree_position: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_all_aiavt_stop: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_get_qing: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  rhythm_main_window: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_lunjian_match_reset: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_lunjian_aiavt_sid: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  get_aiavt_skill_delay_id: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  crash: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  get_surround_tomb_comment: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  show_sync_time: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_aiavt_skill_delay_id: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  atime_c: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  refresh_model: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_change_space_tick_timer: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  crime_big_world_info: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  show_event2: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_skill_gj_leave: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  close_anim_debug_info: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_aiavt_filter_debug: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  use_new_rag: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_move_random: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_client_control_to_client: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  start_dialogs: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.3000cmz.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_destruct_multi: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_debug_collison_sound: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian_lose_ui: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  dump_rpc: function(path)  -- hexm/client/debug/gm/gm_commands/gm_normal.lua:539-554
  reload_sunshine_prefab: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_ailab_trunk: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_preserver_flag: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  crime_run_baoguan_ai: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_move_a: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_mian_player_model_scale: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  match_chiji_target_1: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  GM_CUTSCENE_HIDE_Render: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  forbid_witness_wanfa: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_map_to_player: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_create_ai_by_id: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_choose_server: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_skill_sb: function()  -- hexm/client/debug/gm/gm_commands/gm_normal.lua:2445-2447
  rhythm_rank_window: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  transfer_to: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  naire_clear_mongo: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.60cmz.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lock_post: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  police_is_in_battle: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  crime_get_wit_npc: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_position: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_lunjian_recent_win_num: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_rigidbody_scale: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_makeup: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.6000cmz.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_aiavt_behit_rush: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  get_aiavt_info: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  replace_level: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  debug_transfer_region: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  ai_lab_login: function(ip, port, name, server_port)  -- hexm/client/debug/gm/gm_commands/gm_normal.lua:2949-3007
  gm_aiavt_skill_random: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  draw_space_level: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_all_aiavt_run: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  show_mian_player_pos_tip: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  add_on_crime: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  draw_space_level_default: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.180cmz.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  match_chiji_target_5: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.900cmz.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  mock_stop_record: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  show_anim_debug_info: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian_win_ui: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian11_set_score: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  near_entity: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.battlepassextra.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_show_level_id: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  revert_witness_wanfa: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  transfer_to_by_params: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_create_ai: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  change_to_space: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.6battlepass: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian22_match_player: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.monthlycard.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian11_match_player: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian_quit_match: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  reload_script: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.pspreorder.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  show_event: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  match_chiji_target_change: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  near_boss: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  naire_clear_avt: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  shoubao_gm_ban_ui_xieshi_lock: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  get_one_naire_info: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  cutscene_hide_camera: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_find_server_rpc_exist: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_ailab_llm_audio_text_chat: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_destruct: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  show_rpc: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  change_lunjian_surface_score: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_main_player_listen_fengyun: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  head_unlock: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_skill_lyt: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  forbid_police_wanfa: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_debug_collison_sound_trans_enable: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_test_filter_broadcast: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  atime: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_main_player_charctrl: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  head_select_id: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_control: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  print_hex_signal_debug_info: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_destruct_order: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_play_cutscene: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  cancel_near_entity: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian22_set_score: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_pve_battle_trans: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  add_gameplay_resource: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_destruct_explode: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  naire_clear_avt_and_mongo: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  add_pos: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  no_forbid_police_wanfa: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian_watch_exit: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_pve_battle_ai_range: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  change_lunjian_score: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  change_graph_resource_mode_official: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  ailab_publish: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  debug_game_stop: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  debug_bake_text: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_main_player_dead: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_skill_jump: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.battlepasspro.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_skill_gj_enter: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian_begin_match: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  world_view_all_unlock: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_reload_effects: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  add_river_light: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  draw_aiavt_move_range_id: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  logout_manually: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  mock_stop_play: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  near_build: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  close_console_log: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  dynamic_level_split_x_offset: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  draw_aiavt_move_range: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_clear_all_title: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  modify_lod: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_remove_qing: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_yaw_to_player: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_control_ai_cj: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  no_forbid_witness_wanfa: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  open_log_config: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_pos_player: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  init_network_profiler: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  pvp_battle_accpet_debate: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian_watch_into: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.300cmz.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  draw_aiavt_move_range_player: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  head_unlock_all: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_position_entity: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  start_mob_debug: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  cutscene_hide_light: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian_watch_follow: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_move_d: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  dump_all_property_define: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_create_ai_cj: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.battlepass.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.600cmz.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.1800cmz.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  input_gm: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_debug_collison_sound_trans: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian22_match_robot: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  get_surround_tomb_all_data: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_set_identity: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  MAIN_PLAYER_LOD1: boolean
  enable_move_ctrl: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  add_lunjian_result: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian_exit_record: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  show_gm_transfer: function()  -- hexm/client/debug/gm/gm_commands/gm_normal.lua:4025-4052
  match_chiji_target_ai: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian_force_match: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  show_on_crime: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian33_match_robot: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  setting_reset_position: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian33_set_score: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  crime_pop_ability_fbn: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  draw_aiavt_move_range_clear: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_move_to_player: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_test_glide: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_play_anim: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  enable_mock_recorder: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  clear_recent_gm: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  charge_sid_yysls.12000cmz.oversea: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_change_model: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  debug_pause_hexplugin: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  crime_revert_big_world_info: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  add_cuju: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_test_cook: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_show_game_id: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  match_chiji_target_2: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  process_gm_ban_ui: function()  -- hexm/client/debug/gm/gm_commands/gm_normal.lua:4270-4362
  pvp_battle_get_robot_info: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_move_to_s: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  show_main_player_charctrl: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  unlock_post: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  shoubao_gm_ban_ui: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  change_graph_resource_mode_local: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  update_bin_data: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  mock_play_record: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_find_client_miss_method: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian33_match_player: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_aiavt_move_to_w: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_lunjian_grade: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_main_player_listen: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_destruct_damage: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  change_to_space_without_check: function(space_no, space_id)  -- hexm/client/debug/gm/gm_commands/gm_normal.lua:3043-3050
  goto_proto_map: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  reload_target_script: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_taiji_rigidbody: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_transfer_ignore_region: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_debug_ragdoll: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_anim_warm_up_optimize: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  modify_lod1: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  show_time: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  police_baodi_test: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_denglong: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  set_terrain_landscape: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  change_to_space_sep: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  test_cable: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  run_transfer_seamless: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  level_node_debug: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  input_gm2: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  get_surround_tomb_data: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  mock_start_record: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  change_graph_resource_mode_auto: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian_play_record: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  dec_gameplay_resource: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  unlock_all_title: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  gm_reload_graph: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian11_match_robot: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  is_hide_dialog_light: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  lunjian_manual_page: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  change_lunjian_max_kungfu: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  transfer_to_by_config_no: function(...)  -- hexm/client/debug/gm/gm_commands/gm_oversea.lua:53-58
  ai_lab_confirm_relay: function()  -- hexm/client/debug/gm/gm_commands/gm_normal.lua:3009-3011