Module: hexm.client.debug.gm.gm_commands.gm_task
Type: table
================================================================================

Keys:
  gm_task_open_envelop_window: function
  gm_print_relative_pos: function
  gm_delete_finished_task: function
  gm_game_level_task_unit: function
  gm_open_huijuan_level_tips_window: function
  gm_task_progress: function
  gm_force_fetch_recap: function
  gm_print_doing_task_nos: function
  gm_task_print_region_tasks: function
  gm_abandon_task: function
  gm_force_fetch_task_set_transport: function
  gm_set_ending_value: function
  gm_open_huijuan_chapter_window: function
  gm_we_qiyu_cd: function
  gm_we_chance: function
  gm_clear_ending_value: function
  gm_open_huijuan_window: function
  gm_task_open_hangdang: function
  gm_finish_task: function
  gm_task_set_position: function
  gm_add_task_to_auto_wait: function
  gm_finish_task_with_effect: function
  gm_force_fetch_task: function
  gm_finish_all_task: function
  gm_clear_all_task_data: function
  gm_finish_all_group_task: function
  gm_task_bigmap_focus: function
  gm_open_huijuan_level_window: function
  gm_print_world_pos: function
  gm_task_open_book_window: function
  gm_clear_finished_task: function
  gm_we_cd: function
  gm_we_qiyu_max_num: function
  gm_task_zhuxian_entity: function
  gm_force_fetch_task_finish_track: function
  gm_fetch_task: function
  gm_start_recap: function