Module: hexm.client.consts.collision_consts
Type: table
================================================================================

Keys:
  COLLISION_TYPE_QUERY_ACTOR: number
  COLLISION_TYPE_FULL_CAMERA_COLLIDER: number
  QUERY_BUILD: number
  COLLISION_TYPE_RADIATION: number
  COLLISION_TYPE_QUERY_YUANLING: number
  QUERY_ALL_ENTITY: number
  COLLISION_TYPE_STATIC_WITHOUT_CAMERA_COLLIDER: number
  COLLISION_TYPE_AIRWALL: number
  FILTER_FLAG_PLATFORM: number
  QUERY_LOCK_TARGET_OBSTACLE: number
  COLLISION_TYPE_AIRWALL_EXCLUDE_PLAYER: number
  COLLISION_TYPE_QUERY_STATIC: number
  COLLISION_TYPE_PLAYER: number
  COLLISION_TYPE_QUERY_SUNSHINE: number
  COLLISION_TYPE_WATER: number
  COLLISION_TYPE_ZUOQI: number
  FILTER_FLAG_CLIMB: number
  COLLISION_TYPE_ARROW_AIM: number
  CHECK_CAN_DESTRUCT: function()  -- hexm/client/consts/collision_consts.lua:108-110
  COLLISION_TYPE_FLOWER: number
  MAX_COLLISION_TYPE: number
  QUERY_DYNAMIC_ENTITY: number
  COLLISION_TYPE_BOSS: number
  COLLISION_TYPE_YUANLING: number
  COLLISION_TYPE_QUERY_PLAYER: number
  DESTRUCT_NUM: number
  COLLISION_TYPE_ALL: number
  COLLISION_TYPE_RIDE_NPC_COLLIDER: number
  COLLISION_TYPE_INDOOR: number
  COLLISION_TYPE_SNOW_SURFACE: number
  QUERY_BOSS: number
  QUERY_Sunshine: number
  FILTER_FLAG_STEP: number
  QUERY_STATIC: number
  COLLISION_TYPE_CHECKED: number
  COLLISION_TYPE_WIND_WALL: number
  COLLISION_TYPE_PHYX_OCCLUDER: number
  QUERY_ALL_ENTITY_EXCEPT_MAIN_PLAYER: number
  COLLISION_TYPE_FALL_HURT: number
  COLLISION_TYPE_ARROW: number
  COLLISION_TYPE_DETECT_DANDAO: number
  COLLISION_TYPE_QUERY_WATER_GROUND: number
  QUERY_FoGuang_Light_OBSTACLE: number
  COLLISION_TYPE_FLOATING_OBJECT: number
  FILTER_FLAG_SLIDE: number
  COLLISION_TYPE_NPC_MF: number
  COLLISION_TYPE_STATIC: number
  COLLISION_TYPE_MARSH: number
  COLLISION_TYPE_QUERY_AIRWALL: number
  COLLISION_TYPE_UNDERGROUND: number
  (1 more keys)