Module: hexm.client.consts.keyboard_consts
Type: table
================================================================================

Keys:
  get_richtext_params_by_images: function
  STATE_MOUSE_X2: string
  PAD_LSTICK_DIRECT: number
  get_fixed_engine_keys_by_pc_key: function
  PAD_UP: number
  PAD_Y: number
  get_fixed_click_types_by_pc_key: function
  EInputState_RbDown: number
  STATE_MOUSE_L_MOVE: string
  get_key_dict_by_map_id: function
  STATE_JOYSTICK_R_CURVED_SCROLL: string
  BUTTON_ICON_FILTER: string
  get_joystick_keymap_config: function
  KEY_TAB: number
  STATE_JOYSTICK_R_TRIGGER_RIGHT: string
  KEY_6: number
  PAD_RSTICK_UP_DOWN: number
  get_img_by_map_id: function
  BUTTON_ICON_SHARE: string
  STATE_MOUSE_X1: string
  KEY_RBRACKET: number
  KEY_O: number
  KEY_NUMLOCK: number
  EInputState_None: number
  STATE_JOYSTICK_L_TRIGGER_UP: string
  get_engine_key_config_data: function
  KEY_NUMPAD5: number
  EInputState_NumLock: number
  EInputState_Ctrl: number
  input_state_to_combine_engine_keys: function
  STATE_JOYSTICK_R_TRIGGER_LEFT: string
  get_name_by_map_id: function
  STATE_MOUSE_HIDE_MOVE: string
  KEY_G: number
  PAD_CROSS: number
  STATE_SENSOR_GYROSCOPE: string
  KEY_NUMPAD0: number
  KEY_NUMPAD2: number
  STATE_MOUSE_R_MOVE: string
  PAD_Z: number
  PAD_LS: number
  BUTTON_ICON_RESET: string
  KEY_SLASH: number
  EInputState_JoystickMove: number
  KEY_F5: number
  WM_USER_ATTACH_IME: number
  STATE_SENSOR_ACCELERATION: string
  get_input_func_id_to_map_ids: function
  is_mouse_wheel_engine_key: function
  STATE_JOYSTICK_LEFT_TRIGGER: string
  (1 more keys)