Module: hexm.client.consts.map_marker_consts
Type: table
================================================================================

Keys:
  WULIN_FENGYUN: number
  CHIJI_SANGHUNLIN_SHOP: number
  CLUB_BATTLE_CHEER: number
  ESCORT_BUILD_PLATFORM: number
  GAMEPLAY_PLUGIN: number
  TAVERN_COOK_WANFA: number
  TREASURE_PLAY: number
  CLUB_BATTLE_BOSS: number
  GANG_DRINK: number
  CHIJI_SANGHUNLIN_POS: number
  CLUB_BATTLE_CAMP: number
  GAMEPLAY_JUDIAN: number
  PAINTING_BOAT_BUILDING: number
  GAMEPLAY_EVENT_NEIGONG_LOCATION: number
  WEATHER_NORMAL: number
  DISASTER_WISH_POOL: number
  GAMEPLAY_SINGLE_WANFA_ENTRY: number
  SCHOOL_GUIDE: number
  RUSH_TOWER: number
  MENTOR_NPC: number
  FISHING_CONTEST: number
  GANG_PITCH_POT_PVP: number
  MARKER_STATE_FINISHED: number
  CLUB_BATH_PLUGIN: number
  Suogugong_QIZHEN_SUBMIT: number
  MIAO_MIAO_CAT_TRACE: number
  CLUB_CREATE_PLUGIN: number
  PAINTING_BOAT: number
  DOUDIZHU_GAME: number
  GAMEPLAY_EVENT_DRAGON_INN: number
  GAMEPLAY_STRONGHOLD: number
  DISGUISE_SHOP: number
  SINGLE_WORLD_BOSS: number
  HUAJIANJI: number
  CLUB_PLUGIN: number
  SPACE_INS_ENTITY: number
  FREE_MARKER_TYPE_ROAD_SIGN: number
  ESCORT_HORSE: number
  STUFF_TRACE: number
  CHIJI_SANGHUNLIN_BOX: number
  PAINTING_BOAT_WANFA_TRACK: number
  GAMEPLAY_PRISON: number
  FREE_MARKER_TYPE_SHITU: number
  GAMPLEY_SHOP: number
  FREE_MARKER_TYPE_SHITU_ORI_ID: string
  DISGUISE_NPC_BAG: number
  WEATHER_SUPER: number
  GAMEPLAY_DUNGEON_CLUE: number
  JIEYUAN_WANFA: number
  MAP_LOCK_AREA: number
  (1 more keys)