Module: hexm.client.consts.player_recommend_consts
Type: table
================================================================================

Keys:
  RECOMMEND_TAG_TONGYOU: number
  RECOMMEND_TYPE_COOP_BIG_WORLD: number
  DOCTOR_TAG: number
  BAIYE_SUB_TAG: number
  RECOMMEND_TAG_DOCTOR: number
  RECOMMEND_TAG_LMKZ: number
  RECOMMEND_TAG_PAINTING_BOAT: number
  TEAM_SUB_TAG: number
  RECOMMEND_ORDER_RANDOM: number
  get_recommend_order_by_type: function
  get_recommend_text: function
  ALL_INTELLIGENCE_TAG: list
  RECOMMEND_TAG_INTELLIGENCE_COOP: number
  RECOMMEND_TAG_INTERACT: number
  RECOMMEND_TAG_RECENTLY: number
  RECOMMEND_ORDER_RECENTLY_TEAM: number
  RECOMMEND_TAG_RANDOM: number
  XIUWEI_KUNGFU: number
  RECOMMEND_TAG_RANDOM_TEAM: number
  RECOMMEND_TAG_INTELLIGENCE_TEAM: number
  RECOMMEND_TYPE_COOP: number
  PVP_XS_SUB_TAG: number
  get_recommend_coop_order: function
  CHAQI_SUB_TAG: number
  TANSUO_SUB_TAG: number
  YINGSHENG_SUB_TAG: number
  WUXUE_SUB_TAG: number
  RECOMMEND_TYPE_GHOST: number
  get_recommend_sub_tag: function
  RECOMMEND_TYPE_GIFT_SEND: number
  RECOMMEND_ORDER_OTHERS: number
  RECOMMEND_TAG_FRIEND: number
  RECOMMEND_TAG_COOP: number
  TEAM_BASE_TAG: number
  INTERACT_SUB_TAG: number
  RECOMMEND_TYPE_COOP_SPECIAL: number
  RECOMMEND_TAG_CLUB: number
  get_recommend_text_color: function
  COMBINE_SUB_TAG: number
  TEAM_IN_SUB_TAG: number
  ZHIGE_SUB_TAG: number
  HUIWU_SUB_TAG: number
  TONGYOU_SUB_TAG: number
  RECOMMEND_TAG_NEWSPAPER: number
  LIANJI_TAG: number
  NEWSPAPER_TAG: number
  get_recommend_func_by_tag: function
  XIUWEI_EXPLORE: number
  RECOMMEND_TYPE_TONGYOU: number
  RECOMMEND_TAG_FUNC: dict
  (1 more keys)