Module: hexm.client.consts.setattr_consts
Type: table
================================================================================

Keys:
  RegionGameOccupy: string
  IDENTITY_PVP_DOCTOR_MEDICINE_ITEM: string
  MENTOR_FAVOR: string
  ATTR_MOVE_JOYSTICK_TYPE: string
  FAKE_DEATH: string
  ENTITY_INTERACT_RELATION_INSERT_OR_DEL: string
  TASK_EXTRA_DATA: string
  DYNAMIC_ATTR_1: string
  DUNGEON_ENTITY_ENV_ORDEAL_GUEST: string
  INTERACT_COMPONENT_STATUS_CHANGED: string
  SpaceEffects: string
  BUFENG_CLUE: string
  WENSHI_ANSWER_LIVENESS: string
  BODY_FEAST: string
  MULTI_GUARD_FINISH_REWARD: string
  WANFA_RESOURCE_VALUE_E: string
  ASSESSMENT_PLAYER_EVIL_REPUTATION: string
  DUNGEON_CLIENT_TRAPS: string
  REGION_SNEAK_STATE: string
  ENVIRONMENT_IN_WATER_RANGE: string
  DisasterRescueCamp: string
  MENTOR_BAISHI_POSTS: string
  IDENTITY_PVP_DOCTOR_INFO_ITEM: string
  EXP_RATIO: string
  Skip_Entity: string
  RoomClear: string
  TASK_STATE: string
  PVE_BATTLE_ID: string
  PVP_BATTLE_IN_PREPARE: string
  LangshumijiState: string
  EQUIP_ITEM: string
  AIAVT_HP: string
  SADDLE_BAG_LOAD: string
  PLAYER_MODE: string
  DUNGEON_MUSIC: string
  SKILL_SENSOR: string
  InviteMsg: string
  YINGFU_EXP: string
  DUNGEON_AIRWALL_GUEST: string
  STUFF_INDEX_CHANGED: string
  RegionEventActive: string
  LANGZHONG_POISON_CHANGED: string
  REVERSE_ALERT_TABLE: string
  DUNGEON_WEATHER: string
  ATTR_LIFE_TOXIC_DEF: string
  JiemidongkuRound: string
  LevelReplaceItem: string
  GAME_FORBIDDEN: string
  INTERACT_COMPONENT_LOAD_OR_UNLOAD: string
  ATTR_STATE_ATTR: string
  ENV_ORDEAL_PROP_NO: string
  ATTR_MP: string
  LangshumijiProp: string
  EQUIP_HORSE_ID: string
  PLAYER_STALL_NAME: string
  TEAM_APPLYS: string
  ENHANCE_ITEM: string
  SKILL_GAMEPLAY_ENABLE: string
  NPC_RAY_CHECK_TARGET: string
  append_id: function(event_key, eid)  -- hexm/client/consts/setattr_consts.lua:476-479
  ATTR_GAME_PRIORITY_IDS: string
  SERVER_LEVEL: string
  BODY_DRUNKFEELING_ID: string
  WEAPON_CHANGE: string
  SKILL_LEARNED: string
  TASK_CHAPTER_REWARDS: string
  ENVIRONMENT_AIR_TEMPERATURE: string
  SKILL_ARROW_PROP_EQUIP_ARROW_ID: string
  WORLD_VIEW_CHARACTER_UNLOCK: string
  AIAVT_LOCK_TARGET: string
  DUNGEON_FINISH: string
  IDENTITY_PVP_ANYING_STARTED: string
  AIAVT_BATTLE_TS: string
  room_dispatch_list: list
  RhythmFollowInstrumentFollowing: string
  TASK: string
  COMBAT_IN_BOSS_BATTLE: string
  PORRIDGE_SHOP_ADD_OR_DELETE: string
  KONGFU_SKILL_CLASS_UNLOCK: string
  SchoolStealBox: string
  IDENTITY_PVP_DOCTOR_MATERIAL_ADD_OR_DEL: string
  PVP_WORLD_SHANGJIN: string
  INTERACT_COMP_PROPERTY_EID: string
  INTERACT_ACTIVE_CNT: string
  BIG_WORLD_LEVEL_CONDITION: string
  INTERACT_COMP_SYNC_NUM_OF_CHIJI_DROP: string
  RoomPaoku: string
  REVERSE_AGGRO_TABLE: string
  ENVIRONMENT_MOISTURE_RADIATION: string
  ATTR_SP: string
  NPC_REACTION_ALERT_TABLE: string
  HANGDANG_LANGZHONG_LINK_TARGET_CLEAR: string
  MENTOR_BREAK_PROPOSER_PID: string
  BUILD_EXTRA_COMPONENT: string
  FISHING_PROP_PVP_PROCESS: string
  BUILD_EXTRA_STOVE_STATE: string
  ATTR_ARCHER_FLY_SPEED: string
  KONGFU_LEARN: string
  FACTION_REFRESH: string
  STUFF_INSERT_OR_DEL: string
  WEAPON_LIFT_WEAPON: string
  FUMO_ID_UNLOCK: string
  TEAM_TASK_DATA: string
  INTERACT_COMP_SYNC_EX_EDIT_TS: string
  STUFF_LOCKED_CHANGED_WITHOUT_ID: string
  BODY_FEAST_ID: string
  INTERACT_COMP_ENABLED: string
  WENSHI_ANSWER_HAS_REWARD: string
  MENTOR_SHOUTU_POSTS: string
  StuffLimitChange: string
  NPC_HP: string
  STUFF_NO_CHANGED_WITHOUT_ID: string
  BUILD_EXTRA_STOVE_FIRE_NUM: string
  TOTAL_EXP: string
  KONGFU_ACTIVE: string
  DYNAMIC_ATTR_2: string
  PAINTING_BOAT_AUCTION_DATA: string
  WEAPON_BOW_WEAPON: string
  TEMP_STUFF_INSERT_OR_DEL: string
  WENSHI_ANSWER_ANS_FIRST_CNT: string
  NPC_REACTION_ALERT: string
  IS_ON_RIDE: string
  NpcEffectItems: string
  STUFF_WC_CHANGED: string
  IDENTITY: string
  SKILL_ARROW_MODE: string
  BUFENG_ALL_CLUE_CARDS: string
  REPUTATION_SCORE: string
  NPC_COMBAT_IN_ALERT: string
  DUNGEON_ENTITY_BIG_WORLD_OWNER_LEVEL: string
  REGION_SNEAK_REWARD: string
  INTERACT_COMP_POSITION: string
  JudianPeriodValidProp: string
  PRISON_PARADE: string
  SPRING_FESTIVAL_PARADE: string
  ACTIVITY_INFO_CHANGE: string
  ATTR_LIFE_MIND_DEF: string
  InviteCustMsg: string
  AttachInfoItem: string
  MULTI_GUARD_ALL_FINISH: string
  KONGFU_SUB_CHANGED: string
  BUFF_DISABLE_WALK: string
  NPC_AI_PROCESS_DATA_SET: string
  WANFA_UNLOCK_BY_INTERACT: string
  STUFF_INDEX_CHANGED_WITHOUT_ID: string
  MARSH_STATE_CHANGED: string
  FISHING_PROP_FISH_NO: string
  WORLD_EVENT_DZ_CHANGE2: string
  ATTR_STATE_IN_WALK: string
  CROSS_MATCH: string
  RoomWanfaIndex: string
  COMBAT_MARKED_BY_BOSS: string
  WEAPON_MODE: string
  IDENTITY_PVP_CUR_STATE: string
  INTERACT_COMP_SYNC_ROTATION: string
  STUFF_WC_CHANGED_WITHOUT_ID: string
  SpaceDataCommonCondition: string
  LAND_ON_VEHICLE: string
  RhythmGameSzyyCur: string
  SKILL_SET_CHANGED: string
  SADDLE_BAG_MAX_LOAD: string
  HANGDANG_LANGZHONG_LINK_TARGET_APPEND: string
  BODY_BREATH_ID: string
  ATTR_RESOURCE_EMPTY: string
  FUBEN_SPACE_NO: string
  DUNGEON_SHICHEN: string
  PVP_WORLD_MODE: string
  RegionEventDeActive: string
  ENVIRONMENT_IN_WATER: string
  ENVIRONMENT_AIR_MOISTURE: string
  COMBAT_IN_BATTLE: string
  CommonCondition: string
  PVP_WORLD_CRIME_STATE: string
  RoomMemberUpdate: string
  LangshumijiHasState: string
  CHARACTER_INTEREST_SKILL: string
  AGGROTABLE: string
  CraftSkillsProp_LINGWU: string
  ITEM_EX_DURABILITY: string
  TREASURE_STATE: string
  DUNGEON_LEAF_EFFECT: string
  INTERACT_COMP_YAW: string
  FISHING_PROP_POSITION: string
  NPC_STORE_IS_OPEN: string
  TASK_ONLINE_GROUP_ID: string
  RIDE_SPEED_MODE: string
  PLAYER_CAN_DRAW_MONEY: string
  PLAYER_STALL_IS_OPEN: string
  PORRIDGE_SHOP_CLEAR: string
  RIDE_ENABLE: string
  HANGDANG_LANGZHONG_LINK_EFFECT_APPEND: string
  RegionGamePingbi: string
  RoomMembers: string
  STUFF_NO_CHANGED: string
  GANG_PROPERTY: string
  SHICHEN_CURRENT_SHICHEN_SPEED: string
  SKILL_CD: string
  HANGDANG_LANGZHONG_LINK_EFFECT_CLEAR: string
  WORLD_EVENT_DZ_CHANGE: string
  WORLD_EVENT_LIB_PERSON_CHANGE: string
  STUFF_INSERT_OR_DEL_WITHOUT_ID: string
  KONGFU_MAIN_CHANGED: string
  CraftSkillsProp_Level: string
  WORLD_EVENT_LIB_PERSON_CHANGE3: string
  ENVIRONMENT_TEMPERATURE_RADIATION: string
  RhythmFollowCur: string
  INTERACT_COMP_LOAD_OR_UNLOAD: string
  TUTORIAL_DIASTER_STATE: string
  LOCAL_ENTITY_SYNC: string
  INTERACT_COMP_SYNC_MAX_QUALITY: string
  DYNAMIC_ATTR_E: string
  GUILD_ELECTION_REWARD_STATE: string
  RhythmFollowInstrumentSelected: string
  INTERACT_COMP_SYNC_EX_FIREWORK: string
  AttachInfoBag: string
  SCHOOL_VALUE: string
  BODY_MOISTURE: string
  WENSHI_ANSWER_STATE: string
  WEAPON_ACTIVE_WEAPON: string
  DisasterRescueTriggerTs: string
  BODY_TYPE: string
  BODY_TEMPERATURE_ID: string
  INTERACT_COMPONENT_RELATION_INSERT_OR_DEL: string
  JIEYUAN_DATA: string
  ATTR_STATE_MAP: string
  IDENTITY_PVP_SIGNUP: string
  NPC_COMBAT_IN_BATTLE: string
  JIANGHU_FAME: string
  MAKEUP_NO: string
  MENTOR_BREAK_TIME: string
  MENTOR_REQUESTS: string
  ATTR_HP: string
  IDENTITY_PVP_DOCTOR_CASH_CHANGED: string
  ATTR_LIFE_COLD_DEF: string
  LEVEL: string
  EXP_POOL: string
  BUILDING_CONTENT: string
  ATTR_STATE_IN_CROUCH: string
  BUILD_EXTRA_STOVE_END_TS: string
  MULTI_TRAINING_JOIN_PROP: string
  PORRIDGE_SHOP_INFO_UPDATE: string
  BIG_WORLD_LEVEL: string
  ENVIRONMENT_IN_WATER_DIVING: string
  IN_RIDE_NAVIGATE: string
  AIAVT_ACTION_TYPE: string
  SADDLE_BAG_SLOT_UPDATE: string
  DYNAMIC_ATTR_3: string
  AIAVT_DEFENCE: string
  BUFENG_ALL_MILING: string
  TASK_ONLINE: string
  IDENTITY_PVP_DOCTOR_STARTED: string
  SHICHEN_CURRENT_SHICHEN: string
  ATTR_LIFE_HOT_DEF: string
  BODY_TEMPERATURE: string
  BODY_DRUNKFEELING: string
  LevelReplaceConfig: string
  IDENTITY_PVP_DOCTOR_CASH_CHANGED_EVENT: string
  IDENTITY_PVP_DOCTOR_MEDICINE_BAG: string
  DUNGEON_AIRWALL: string
  SCHOOL_WISDOM: string
  COMBAT_BATTLE_MODE: string
  ASSESSMENT_PLAYER_REPUTATION: string
  GANG_MEMBERS: string
  SWALLOW_TASKS: string
  STRONGPOINT_PASSED: string
  TEAM_LEADER: string
  Xinfa: string
  BAIYE_BATTLE_TOKEN: string
  FreeMusicInstrument: string
  BUFENG_SELECT_CLUE_CARDS: string
  JiemidongkuDoneData: string
  TEAM_MEMBERS: string
  DYNAMIC_ATTR_10004: string
  TASK_GUIDE_MODE: string
  MENTOR_PROP: string
  WORLD_VIEW_FORCE_UNLOCK: string
  ENV_ORDEAL_FORBID_EFFECT: string
  MENTOR_REQUEST_STATE: string
  BODY_CONCENTRATION_ID: string
  CaveLevelInteract: string
  SpaceEffectLevel: string
  WEATHER_CURRENT_WEATHER_ID: string
  COMPOUND_ANVIL_PLACED_BAG: string
  WORLD_EVENT_LIB_PERSON_CHANGE2: string
  HANGDANG_LANGZHONG_LINK_TARGET_POP: string
  SWALLOW_SEASON: string
  KONGFU_FIRST_UNLOCK: string
  TASK_TRACK_CHANGE: string
  BODY_MOISTURE_ID: string
  TASK_FINISH_MAP: string
  COMBAT_BOSS_ID: string
  PITCH_POT_STATUS: string
  PAINTING_BOAT_NAVIGATION_DATA: string
  DUNGEON_EFFECT_LISTS: string
  BUFENG_CUR_MILING_ID: string
  DIST_WANFA_ASYNC_FLAG: string
  RoomTeamId: string
  DYNAMIC_ATTR_5: string
  BODY_BREATH: string
  EntityStatus: string
  STUFF_LOCKED_CHANGED: string
  RegionGameLoaded: string
  PRISON_PARADE_TIMES: string
  BODY_CONCENTRATION: string
  GuildProp_GUILD_NUM: string
  PVP_WORLD_REVENGE: string