Module: hexm.client.consts.share_consts
Type: table
================================================================================

Keys:
  FIXED_SIZE_SHARE_TYPE: list
  SHARE_CHANNEL_NAME: dict
  SHARE_DATA_OK: string
  SOCIAL_LINE: number
  MAX_SHOW_FREIND: number
  SOCIAL_KUAISHOU: number
  FRIEND_EXTRA_MENTOR: number
  SOCIAL_GODLIKE: number
  sort_chat_group: function
  SOCIAL_PLATFORM_FACEBOOK_MESSENGER: number
  SOCIAL_SINA_WEIBO: number
  SOCIAL_WEIXIN: number
  CLOUD_SOCIAL_PLATFORM_CHANNELS: dict
  SOCIAL_PLATFORM_WEIXIN: number
  SHARE_SIDE_GAMEPLAY: number
  dummy_recommend_rule: function
  SHARE_CHANNEL_TAB: number
  SOCIAL_PLATFORM_TWITTER: number
  SOCIAL_PLATFORM_QQ: number
  SHARE_VIDEO: number
  SHARE_SIDE_FRIEND: number
  SOCIAL_DOUYIN: number
  PS_SHARE_TYPE_PICTURE: number
  RECOMMEND_RULE_DICT: dict
  SOCIAL_FACEBOOK_MESSENGER: number
  RECOMMEND_EXTRA_HOARD_PROFITEER: number
  REQUEST_MORE_DATA_OK: string
  SHARE_WORLD_VIEW_KAOJU: number
  SHARE_FRIENDS_TAB: number
  get_share_card_local_key: function
  SOCIAL_WHATSAPP: number
  SOCIAL_TWITTER: number
  SOCIAL_WEIXIN_PENGYOUQUAN: number
  SOCIAL_PLATFORM_LINE: number
  SHARE_TYPE_SHARE: number
  SOCIAL_LINE_GAME: number
  SOCIAL_QQ_ZONE: number
  SOCIAL_QQ: number
  SHARE_CHANNEL_PARAM: dict
  CLOUD_SOCIAL_PLATFORM_NAMES: dict
  SOCIAL_TIKTOK: number
  SOCIAL_PLATFORM_DOUYIN: number
  SHARE_COMMON_PHOTO: number
  SOCIAL_PLATFORM_YIXIN: number
  SHARE_INVITATION_GAMEPLAY: number
  SOCIAL_PLATFORM_SINA_WEIBO: number
  FRIEND_EXTRA_ZUIHUAYIN: number
  get_share_default_tab: function
  FRIEND_EXTRA_TEAM: number
  SOCIAL_YIXIN: number
  (1 more keys)