Module: hexm.client.consts.task_panel_consts
Type: table
================================================================================

Keys:
  PRIORITY_JUDIAN: number
  ITEM_HINT_MODE_HINT: number
  PRIORITY_SCHOOL_JL_PUNISHMENT: number
  WANFA_PRISON: number
  PRIORITY_MULTIPLAYER_THERAPY: number
  generate_task_item_controller_dict: function
  TASK_PANEL_REDPOINT_KEY: string
  TASK_DRAGON_INN: number
  PRIORITY_MULTIPLAYER_ANTIQUE_AUCTION: number
  PRIORITY_MAX: number
  PRIORITY_TASK: number
  PRIORITY_MULTIPLAYER_ARCHERY: number
  ITEM_HINT: number
  WANFA_PAINTING_BOAT: number
  WANFA_SCHOOL: number
  ITEM_HINT_MODE_FAILED: number
  ITEM_MULTI_BTN: number
  JIEYUAN_ANSWER: number
  TASK_ONLINE_GUEST_TIP: number
  PRIORITY_LONGMEN_INN_NIGHT_TALK: number
  PRIORITY_NEIGONG: number
  TASK_TEMP_TRACK_MODULE: number
  get_show_module_template_clz: function
  TASK_LIANJI_MODULE: number
  WANFA_MULTIPLAYER_THERAPY: number
  WANFA_ANTIQUE_AUCTION: number
  WANFA_NEIGONG: number
  ITEM_CONTENT: number
  ITEM_BUTTON: number
  TASK_PANEL_GP_TEMP: number
  TASK_HUD_PC_KEY_NO_DICT: dict
  PRIORITY_THEATER: number
  TASK_DEFAULT_TASK_TYPE: number
  CLUB_HUD_ENTRY: number
  CHIJI_HUD_SAFE_ZONE_INFO: number
  PRIORITY_YANHUA: number
  PRIORITY_ORDER: number
  WANFA_ANSWER: number
  WANFA_GYMNASTICS: number
  TASK_BTN_3: number
  PRIORITY_CHIJI_GAMEPLAY_TASK: number
  WANFA_THEATER: number
  TASK_BTN_2: number
  PRIORITY_DRAGON_INN: number
  get_task_item_controller: function
  TASK_FINISH_MODULE: number
  ITEM_LIST: number
  WANFA_MULTI_MWZX: number
  WANFA_JUDIAN: number
  PRIORITY_GYMNASTICS: number
  (1 more keys)