Module: hexm.client.manager.setting.setting_config
Type: table
================================================================================

Keys:
  EDIT_STATE_NORMAL: number
  SETTING_CAMERA_MOVESPEED_X: string
  SETTING_JOYSTICK_GYROSCOPE_RATE: string
  SETTING_PRELOAD_SIGN_VISIBLE: string
  SETTING_BUILDING_FREE_CAMERA: string
  SETTING_CAMERA_Y_REVERSE: string
  SETTING_MOBILE_FLY_CONTROL_MODE: string
  SETTING_ALLOW_STRANGER_CHAT: string
  SETTING_LOCK_CAMERA: string
  SETTING_VOICE_OUTPUT_TYPE: string
  SETTING_SUB_WEAPON_HIDE: string
  SETTING_CONFIG_HOOK: dict
  SETTING_BOW_WEAPON_HIDE: string
  SETTING_TYPE_SWITCH_NEW: number
  SETTING_SELF_SIGN_VISIBLE: string
  SETTING_MOBILE_NORMAL_NONLINEAR_VELOCITY_MODE_Y_RATE: string
  SETTING_TYPE_NOTIFY: number
  SETTING_OTHER_SIGN_VISIBLE: string
  SETTING_CHALLENGE_SECOND_PASSWORD: string
  SETTING_LAND_NOTIFY: string
  SETTING_MOBILE_AVATAR_LOD1_FORBIDDEN_ANDROID: string
  SETTING_DANMU_HUD: string
  SETTING_SOCIALIZE_SECOND_PASSWORD: string
  SETTING_SALOG_KEY: dict
  SETTING_WHITEPOINT: string
  SETTING_NOTIFY_ENABLE: string
  _get_difficulty_setting_config: function(setting_key)  -- hexm/client/manager/setting/setting_config.lua:374-426
  SETTING_SIGN_INVITE: string
  SETTING_PICTURE_STYLE: string
  SETTING_PLAYER_NOTIFY: string
  SETTING_SHOW_MOUSE_MODE: string
  SETTING_SUPER_RESOLUTION: string
  SETTING_XIAOZUJIAN_ONLINE: string
  SETTING_RECORD_VIDEO_GAME_TAIJI: string
  SETTING_BRIGHTNESS: string
  SETTING_ALLOW_OTHERS_SEARCH: string
  SETTING_BUILDING_USE_MINE: string
  SETTING_MOBILE_NPC_QUALITY: string
  CHATROOM_FRIEND_SHARE: string
  SETTING_CAMERA_DIRECTION_CORRECTION: string
  SETTING_FASHION_EFFECT_HIDE: string
  SETTING_RECORD_VIDEO_QUALITY: string
  SETTING_BUILDING_ATTACK_ENABLE: string
  SETTING_MOBILE_NORMAL_CAMERA_CONTROL_MODE: string
  SETTING_BUILDING_GRID: string
  SETTING_TYPE_ONLY_CHECK: number
  SETTING_MOBILE_GYROSCOPE: string
  SETTING_MOBILE_AIM_CAMERA_NONLINEAR_VELOCITY_MODE_Y_RATE: string
  SETTING_JOYSTICK_MOTION_RATE: string
  SETTING_CCMINI_ENHANCE_BG: string
  (1 more keys)